### ISSUE TITLE
Refaire le site internet

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#1]
- [ ] Splitter en plusieurs pages
- [x] Mettre en avant nos commanditaires
- [x] Réduire le bullshit de texte
- [x] Éliminer le besoin de changer le code pour updater nos événements et CE

**Comment by Res260** [comment]
So on a pas de CMS?

**Comment by Sytten** [comment]
Non en effet et on veut pas vraiment en maintenir un mais on pourrait avoir un genre de Jekyll

**Comment by Pourliver** [comment]
J'ai entendu parler pas mal de Jekyll, vu qu'on a probablement pas besoin d'un backend ça serait une bonne idée

**Comment by Res260** [comment]
I mean c'est pas dûr maintenir un CMS en même temps

**Comment by Sytten** [comment]
Non c'est sûr, juste qu'on a plus de serveur en ce moment et ça me tente pas vraiment d'en maintenir un. SInon on pourrait juste avoir une petite DB firebase.

**Comment by maximevaillancourt** [comment]
Si on veut avoir un blog éventuellement, Jekyll semble être l'idéal, surtout qu'on pourrait continuer d'héberger le site avec GitHub Pages. Sinon, y'a [Hugo](https://gohugo.io/) ou [Gatsby](https://www.gatsbyjs.org/) qui ont l'air bien. On pourrait même utiliser un «presque-CMS» comme [Forestry.io](https://forestry.io/) (vraiment intéressant!).

Les deux problèmes principaux avec le site en ce moment sont les suivants : 

**1. Modification de contenu pénible**
C'est gossant de modifier le contenu manuellement dans le HTML à chaque début de session, donc ça prendrait un genre de fichier de configuration qu'on peut mettre à jour facilement et qui modifie le contenu des pages sans devoir écrire du HTML à chaque fois (par exemple, un fichier `config.json` qui contiendrait trois catégories de données : 

- `equipe` (pour les noms et photos des membres du CE)
- `commanditaires` (pour les noms et logos des commanditaires)
- `evenements` (pour les noms, logos et dates des événements)

**2. Contenu peu pertinent, trop lourd, pas assez clair**
On doit retravailler le message qu'on essaie de partager avec les visiteurs du site. Le contenu actuel est trop lourd et n'arrive pas à faire comprendre au non-initié ce que JDIS fait. Pour corriger ça, on peut simplement partir _from scratch_ et réécrire le contenu du site dans un registre plus familier, plus proche de nos membres.

Voici, à titre d'exemple, le site Web de la DCI.

![image](https://user-images.githubusercontent.com/8457808/38708692-754c3222-3e85-11e8-8145-591af3b81013.png)

Il est très agréable à l'oeil, et c'est facile de comprendre leur mission dès la première visite. Point super important sur leur page d'accueil : les commanditaires sont positionnés juste en dessous du hero, donc ils sont bien visibles.

-----

Bref, on doit commencer le développement du nouveau site avec ces points-là en tête.

**Comment by Res260** [comment]
- Mettre "Jeux et Défis Informatique Sherbrooke" dans le `title` du site :)

**Comment by FelixMartel** [comment]
- http**s**://jdis.ca redirige vers http://www.jdis.ca 😠

**Comment by Sytten** [comment]
Thats fucking sad XD

**Comment by Res260** [comment]
yeah un tsi Lets encrypt devrait pas être dur à set rite?

**Comment by Sytten** [comment]
Pas tellement besoin on est derriere cloudflare

**Comment by Res260** [comment]
I mean ça empềche pas un ISP d'insérer du code JS AFAIK


--Émilio

**Comment by Sytten** [comment]
I meant que le site est SSL entre le user et cloudflare. Le seul bout pas SSL cest entre cloudflare et github, mais on sen fou pas mal.

**Comment by Res260** [comment]
Y'a tu quelque chose qui vous intéresse là-dedans? http://jekyllthemes.org/

**Comment by Res260** [comment]
J'aime bien lui https://iwiedenm.github.io/jekyll-theme-massively/elements/

**Comment by Sytten** [comment]
C'est clean mais faudra adapter a nos couleurs

**Comment by Res260** [comment]
yeah of course


--Émilio

**Comment by Res260** [comment]
c'est correct jsuis un master du css hihi



--Émilio

**Comment by Res260** [comment]
est-ce qu'on a vraiment besoin d'une version en anglais du site?

**Comment by Res260** [comment]
Huhhh le thème que j'aimais se base sur un gros background, so ça serait dur de placer les sponsors en avant :(

**Comment by Res260** [comment]
Sinon y'a lui si on aime le material theme http://jekyllmaterialize.panoramedia.it/

**Comment by Res260** [comment]
Rencontre mercredi soir pour discuter du site Web

**Comment by Res260** [comment]
Vu que jvais être plus occupé avec le iHack est-ce qu'on peut l'assigner à quelqu'un d'autre?

**Comment by Sytten** [comment]
Faudrait remettre ça en priorité @Res260 c'est important comme vitrine pour les commanditaires

**Comment by Res260** [comment]
Ouain faudrait que je m'y remettes mais man jsuis perdu seul since on a décidé de faire ça from scratch au lieu de prendre un thème déjà fait

**Comment by Sytten** [comment]
ouais I guess qui faudrait y aller tranquillos

**Comment by Sytten** [comment]
@maximevaillancourt est-ce qu'on progrès de ce côté?

**Comment by maximevaillancourt** [comment]
Oui, je suis là-dessus dans mes temps libres. ETA: deux semaines.

**Comment by maximevaillancourt** [comment]
Pour vous donner une idée du style que je compte adopter :

----

![2018-09-07-090830_1349x627_scrot](https://user-images.githubusercontent.com/8457808/45220875-ab560e80-b27d-11e8-975e-4f9a528a9795.png)

----

Le but, c'est de créer un narratif, une histoire que l'internaute pourra lire afin de mieux comprendre la mission de JDIS (au lieu des bullet points au contenu vide sur le site actuel). On parle aussi de contenu riche—photos, vidéo, tweets, posts Facebook—directement imbriqués sur la page.

Vraiment pas certain du logo. Voir https://github.com/JDIS/Organisation/issues/28 pour plus d'infos.

Pas encore certain de l'overlap du texte et de l'image non plus. Je vais continuer mon exploration.

**Comment by Res260** [comment]
Nice! Mais ouain actuellement l'overlap est wack :)

**Comment by Sytten** [comment]
C'est clean, mais ça serait bien un peu de vert aussi selon le logo qu'on choisi :)

**Comment by Res260** [comment]
@maximevaillancourt Y reste quoi à faire?

**Comment by maximevaillancourt** [comment]
@Sytten parlait d'avoir des pages dédiées pour l'équipe, les événements, nos sponsors, et autres, mais je suis pas certain que ce soit nécessaire. Ce serait quoi l'avantage d'avoir des pages dédiées? Pour le SEO? Je considère surtout que c'est plus de trouble à maintenir qu'un one-pager.

**Comment by Res260** [comment]
Will close for now, on fera des issues séparées par feature souhaitées.
