### ISSUE TITLE
Organiser la collecte des CV

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#104]

**Comment by Res260** [comment]
Y'a une option de file upload sur GDrive, je teste

**Comment by Res260** [comment]
Ça marche relativement bien.

**Comment by Res260** [comment]
Yeah on va fonctionner avec le form from now on
https://docs.google.com/forms/d/1nHRmaeXhlUoQoLvrfg2sl4asG_pCRGsjseFsOF6jhYI/edit#responses
Les CVs sont uploadés sur le drive de JDIS
