### ISSUE TITLE
delete static website?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#108]
Est-ce qu'on se sert de ce repo?
https://github.com/JDIS/static-website

**Comment by Res260** [comment]
@maximevaillancourt @Sytten

**Comment by maximevaillancourt** [comment]
Je ne vois pas d'inconvénient à le laisser archivé. Pourquoi le supprimer entièrement?

**Comment by Res260** [comment]
Woah j'avais pas vu qu'il était archived my bad
