### ISSUE TITLE
Renouvellement des commandites

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#11]
Quelques commandites viennent à échéance bientôt. Nous devons poker les compagnies pour assurer le renouvellement et s'assurer de leur satisfaction par rapport au plan de commandite.
Profitons-en aussi pour regarder avec elles les possibles activités dont ils pourraient être partenaires.

**Comment by urospet** [comment]
Message envoyé à Covoe, Desjardins
Emilio s'est occupé de Sherbrooke Innopole
