### ISSUE TITLE
Effectuer les retours de fonds

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#110]
- [x] REMDUS
- [ ] RECSUS

**Comment by Sytten** [comment]
Bergy a fait la demande, mais je suis pas certain si tout est correct. On va faire le follow-up en revenant.

**Comment by Res260** [comment]
@Sytten Update?

**Comment by Sytten** [comment]
J'ai fini le REMDUS, demain je vais aller voir le RECSUS pour voir qu'il en est.

**Comment by Sytten** [comment]
RECSUS poké, pas eu de réponse. Je vais revoir ça milieu de semaine prochaine.

**Comment by Sytten** [comment]
RECSUS va nous faire le chèque cette semaine.

**Comment by Res260** [comment]
350$ du recsus, we good
