### ISSUE TITLE
Faire le ménage du drive

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#112]
J'aimerais bouger le plus de trucs possible vers Github.

**Comment by Res260** [comment]
Y'a quoi à bouger?

**Comment by Sytten** [comment]
eventuellement jaimerais que tout ce qui bouge pas dans le temps soit dans github, genre les rapports et les proces verbaux.

**Comment by Res260** [comment]
Imo les procès verbaux devraient rester sur le drive

**Comment by Res260** [comment]
J'ai clean le drive en déplaçant beaucoup d'outdated stuff dans des dossiers "archives", plus facile un peu à se retrouver
