### ISSUE TITLE
Followup des conférenciers

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#113]
- Donner le lien youtube
- Donner le feedback des gens (demander à @Res260)
- Remercier

TODO:
- [ ] Hopper
- [ ] Coveo
- [ ] SAP
- [ ] Nexapp
- [ ] GRIIS

**Comment by Res260** [comment]
@Sytten @samdus update?

**Comment by Sytten** [comment]
Jai pas les miens Im bad, jai juste pas le gout de travailler sur jdis en ce moment

**Comment by Res260** [comment]
Rendu un peu tard pour ça :(
