### ISSUE TITLE
Relancer Screeps

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#12]
Nous avions démarré un serveur Screeps, mais l'idée est pas mal tombée à l'eau faute de réel engagement de la communauté.
Il serait possible pour JDIS d'acheter un bulk de clés (nous avons déjà contacté l'éditeur à ce sujet).
Il serait intéressant de voir si d'autres universités seraient intéressé à participer histoire de mettre un peu de challenge.

**Comment by Res260** [comment]
Qu'est-ce qui serait différent pour que ça tombe pas à l'eau cette fois-ci?

**Comment by Sytten** [comment]
Faire de la promotion principalement, on a pas vraiment annoncé ça l'automne passé. Il faudrait faire un event pour expliquer le jeu et avoir des clés pour tout le monde (environ 200$ de dépense)

**Comment by Res260** [comment]
Je propose qu'on se concentre sur ce qui a été discuté en CE principalement (actually je dis ça pour pas qu'on ait trop d'Issues d'ouvertes), thoughts?

**Comment by Sytten** [comment]
Ouais je vais le fermer pour cette session
