### ISSUE TITLE
Mettre la banner sur la porte?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#120]
WILD IDEA

Ça fitte j'ai checké hihi

**Comment by Sytten** [comment]
Pas certain que les profs vont apprécier

**Comment by Res260** [comment]
Pourquoi les profs aimeraient pas? C'est notre local lmao

**Comment by Sytten** [comment]
Ca marche pas de meme RIP

**Comment by Res260** [comment]
Ouain mais pourquoi y chialeraient lol

**Comment by Sytten** [comment]
Ma texpliquer demain

**Comment by Sytten** [comment]
Voir https://github.com/JDIS/Organisation/issues/125
