### ISSUE TITLE
Midi-conférence #3: Sherweb

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#121]
3 avril

@Sytten Besoin des détails

**Comment by Res260** [comment]
Alright, t'as un titre, description?

**Comment by Sytten** [comment]
Non pas encore, je pensais deleger la tache a notre prochain vp conferences

**Comment by jolafreniere** [comment]
J'ai forward le mail avec titre/description à @Res260

Le D7-3021 est réservé le 11 avril de 12h30 à 13h30

**Comment by Res260** [comment]
À quel email? Je le vois pas

--Émilio

**Comment by jolafreniere** [comment]
Ouais y'a confusion. C'est pas le 11, c'est le 3

**Comment by jolafreniere** [comment]
Je passe réserver le 3 demain

**Comment by Blond11516** [comment]
https://www.facebook.com/events/442253186544265/

J'attend la confirmation que le local est réservé pour poster.

**Comment by Res260** [comment]
le présenté par sherweb est pas hyper centré

--Émilio

**Comment by Res260** [comment]
also jpense pas qu'ils fournissent des breuvages?

--Émilio

**Comment by Res260** [comment]
Also je mettrais Domain Driven Design au lieu de DDD, c'est pas clair comme
titre

--Émilio

**Comment by Blond11516** [comment]
Can't do, le titre actuel rentre flush dans 64 caractères...

**Comment by Blond11516** [comment]
J'ai fixé le reste

**Comment by Res260** [comment]
kk

--Émilio

**Comment by Res260** [comment]
@jolafreniere ça a été réservé?

**Comment by Res260** [comment]
31 personnes, assez technique/niche comme talk, j'ai aimé mais jpas sûr que ctun consensus
