### ISSUE TITLE
Changer l'affiche sur la porte du local

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#125]
Elle commence a dater.
Je propose qu'on en fasse une plus grosse.
Budget: 20-30$

**Comment by Res260** [comment]
Design (retrouver le design des banners roulantes), imprimer, trouver la taille
Considération: pas changer l’affiche quand nos sponsors changent, mais les inclure xd

**Comment by Res260** [comment]
@ArcticWalrus Est-ce que t'as une idée de design? Ça peut être ben simple

**Comment by ArcticWalrus** [comment]
J'ai commencé à regarder ça. Je vais essayer d'avoir une version de fait en fin de semaine.

**Comment by Res260** [comment]
À mettre:
Liens vers notre slack (jdis.slack.com)
Facebook: JDISherbrooke
Lien vers notre site: jdis.ca

**Comment by ArcticWalrus** [comment]
Quelle taille est-ce qu'on voudrait : https://uni-d.ca/produit/impression-affiches-photo/

**Comment by Sytten** [comment]
24x36 devrait etre bon?

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/64640291-a28ba180-d3d7-11e9-88c3-721b04d75e7f.png)

**Comment by ArcticWalrus** [comment]
@Pourliver 24x36

**Comment by Pourliver** [comment]
Combien de commanditaires doivent être sur la porte? Est-ce qu'on peut juste leur imprimer des mini-bannières et les laisser sur notre porte? C'est fucking attroce logo + liens + commanditaires, on perds trop de place.

**Comment by Goglu023** [comment]
On demande une seule impression de 24po X 36po chez [Walmart](https://photos3.walmart.com/category/332-poster-prints?product=2159-poster-24x36&theme=wmfullphoto-1.themepack%3A24x36.poster&design_code=standard.fullphoto) pour $20.86. Simplement utiliser l'image source de la bannière

**Comment by MYSTACK555** [comment]
affiche commander

**Comment by Capucinoxx** [comment]
Afficha posée sur la porte du local 
![image](https://user-images.githubusercontent.com/42392217/146450653-dc3c3334-d50a-421c-9bca-2a06bb024888.png)
