### ISSUE TITLE
Photo des membres du CE

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#129]
Pour le site

**Comment by Res260** [comment]
@JDIS/ce Merci de partager une photo CARRÉE pour le site ici

**Comment by Res260** [comment]
@Pourliver T'en profiteras pour remplacer `200 étudiant-e-s` par `250 étudiant-e-s` :)

**Comment by Blond11516** [comment]
Est-ce qu'on post les photos en comment ici ou on les envoie à quelqu'un?

**Comment by Res260** [comment]
post en commentaire ici

**Comment by tihbe** [comment]
<img src="https://user-images.githubusercontent.com/9361364/51484552-dee79000-1d69-11e9-9533-b23ccc91cce6.jpg" width="100">

**Comment by Res260** [comment]
@MAGNUM81 @jolafreniere Manque vous deux

**Comment by Res260** [comment]
also @deltaspace mais jpeux pas le mention xd

**Comment by Pourliver** [comment]
J'vais faire un rappel au CE.

**Comment by Res260** [comment]
@jolafreniere @MAGNUM81 photo...

**Comment by Deltaspace42** [comment]
![50320742_366723990818947_7107851664320626688_n](https://user-images.githubusercontent.com/31398565/51775070-775f7680-20c2-11e9-9ba9-58e1cdbc0e4d.jpg)

**Comment by Res260** [comment]
Jo et Gill ont envoyé leur photo à max en privé xx

**Comment by Res260** [comment]
pushed
