### ISSUE TITLE
Recherche de nouveaux commanditaires

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#13]
JDIS est toujours à la recherche de nouveaux commanditaires donc si vous avez des contacts ou des noms qui vous viennent en tête, partagez-les!
- PMCTire
- CGI Sherbrooke
- Wolters Kluwer (réessayer)

**Comment by Res260** [comment]
CGI ont déjà été poké?

**Comment by Sytten** [comment]
non je crois pas

**Comment by Res260** [comment]
Jpourrais les contacter, jsuis en bon terme avec un gestionnaire chez CGI Sherbrooke.

**Comment by Pourliver** [comment]
PMCTire ont une superbe de belle gang. Mon coloc a un stage là-bas, et ils sont super intéressés par les dernières technologies et par la sécurité. Je peux en parler avec mon coloc pour m'informer, mais à voir.

**Comment by Res260** [comment]
Jviens de poke un ami chez cgi, ils commanditent déjà TechnoDrinks donc y sont probablement ouverts, y va tâter le terrain quand on aura refait le olan de commandites

**Comment by Sytten** [comment]
C'est beau, faudra faire ça rapidement je crois.

**Comment by Pourliver** [comment]
Pareil pour PMCTire, ils commanditent aussi les TechnoDrinks.

**Comment by urospet** [comment]
Wolters Kluwer? qu'est ce qui s'est passé avec eux @Sytten  j'ai vu qu'ils nous avaient commandité de 1150$ en 2016

**Comment by Res260** [comment]
On pourrait les repoke I guess? Pareil pour PMCTire

**Comment by Sytten** [comment]
On pourrait, mais ils ont eu de la misère dernièrement à recruter et notre commandite les a pas vraiment aidé j'imagine.

**Comment by Res260** [comment]
idk on peut miser sur notre nouveau plan? :^)

**Comment by Res260** [comment]
Voir #44
