### ISSUE TITLE
Deal avec midi-conférence #2

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#136]
Date: 13 février

Savoir ce qu'on fait, rapidement: bentley? Sponsor potentiel? Félix Vigneau?

**Comment by Sytten** [comment]
@JDIS/ce Est-ce qu'on a des news?

**Comment by Res260** [comment]
Courriel envoyé hier par gill

**Comment by Res260** [comment]
Félix Vigneault va donner le talk.
