### ISSUE TITLE
Pratique #2: sécurité

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#137]
[] Faire l'événement fb
[x] Réserver local
[] Préparer mini-présentation
[] pub

**Comment by Res260** [comment]
Event fb https://www.facebook.com/events/2215749732012898/

**Comment by Res260** [comment]
À faire: pub génie, pub sciences, emails (?), pub groupe membres jdis

**Comment by Res260** [comment]
Pub sciences pub groupe membres done

**Comment by Res260** [comment]
@Sytten ou @tihbe peux-tu faire la pub dans les groupes de génie?

**Comment by Res260** [comment]
Emails envoyés

**Comment by Pourliver** [comment]
Ça c'est bien passé. Pas beaucoup de gens, mais ya une petite gang intéressé et motivé je crois.

Vendredi Hacking?????
