### ISSUE TITLE
JDIS Games: Rencontre #1

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#139]
La première rencontre vise à commencer le plus tôt possible la conception (si nécessaire) du jeu à utiliser pour JDIS Games.

@DrPandemic Je sais que t'as dit que tu ferais pas de jeu cette année, mais j'ai cru bon de te mettre in the loop, car tu avais quelques idées tout de même!

Points à aborder pendant la rencontre:
- Distribution des tâches
- Décider si on fait un jeu
- Si oui, brainstorm et déterminer les grandes lignes telles que: format (long running?), pt langage de prog, règles de base

**Comment by Res260** [comment]
Date JDIS Games de l'année passée:  samedi 14 juillet 2018

**Comment by Pourliver** [comment]
Je propose le 30 janvier?

**Comment by AntoineTheb** [comment]
Une idée de jeu: Pacman capture the flag. Ça serait pas trop dur à setuper je crois
http://ai.berkeley.edu/contest.html

**Comment by AntoineTheb** [comment]
Donc 30 Janvier toujours valide ?

**Comment by Res260** [comment]
GH Project créé.
