### ISSUE TITLE
Northsec: former des équipes

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#141]
Est-ce qu'on peut envoyer deux équipes cette année? Might be a stretch

**Comment by Pourliver** [comment]
La délégation existe depuis maintenant 3 jours, et on a déjà plus de 8 personnes inscrites. Il risque donc d'y avoir **au minimum** 2 équipes... Hype? :tada:

**Comment by Res260** [comment]
Deux équipes formées!
