### ISSUE TITLE
Contacter Nexapp pour commanditer JDIS

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#143]
👀  @Blond11516 S'en occupe

**Comment by Res260** [comment]
@Blond11516 Make sure de mettre vp.commandites@jdis.ca en CC dans tes communications par courriel

**Comment by Blond11516** [comment]
Est-ce que j'attends le plan de commandite 2019 ou je le fais tout de suite?

**Comment by Res260** [comment]
Commence tout de suite, tu peux utiliser le plan de commandites 2018, le 2019 va pas FULL changer

**Comment by Blond11516** [comment]
Est-ce que je commence tout de suite à parler de la possibilité d'un midi-conférence ou on préfère attendre de clarifier la relation commandite-midi-conférence avant?

**Comment by Res260** [comment]
Tu peux lui parler de la possibilité à l'hiver mais que c'est pas garanti, sinon ça peut être à l'été ou plus tard I guess? @sytten @MAGNUM81 vous en pensez quoi?

**Comment by MAGNUM81** [comment]
C'est une bonne strat. Aucune objection à l'exécution de ce plan.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Res260** [comment]
Vas-tu contacter bentley tout de même @MAGNUM81 ?

**Comment by Blond11516** [comment]
Courriel envoyé. J'ai gardé le courriel friendly, le nom complet du gars est Alexandre Walsh. Est-ce que je close l'issue ou on attend d'avoir une réponse?

**Comment by Res260** [comment]
On attend. Est-ce que t'as cc vp.commandites?

**Comment by Blond11516** [comment]
yup

**Comment by MAGNUM81** [comment]
C'est un super beau message que tu as fait là mon blond! Fier de toi! I guess qu'on peut modifier l'issue ou en créer une autre pour "Faire le suivi sur OP Nexapp"

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Res260** [comment]
Comme vous préférez, perso jtrouve ça plus simple garder cette issue

**Comment by MAGNUM81** [comment]
True dat.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by MAGNUM81** [comment]
whoa jvais essayer de pu trop reply avec outlook ça met de la crap partout :o

**Comment by Res260** [comment]
cpas si pire y'a un `...` qui cache tout

**Comment by Res260** [comment]
Nexapp deviendra commanditaire i3 (500$), @MAGNUM81 Prend la relève

**Comment by Sytten** [comment]
Je peux faire la facture si c'est officiel, est-ce qu'on change le plan de commandite avant?

**Comment by Res260** [comment]
On le change pas avant, les changements seront trop mineurs pour qu'on bother

**Comment by MAGNUM81** [comment]
Donc, comment on procède? Je leur envoie un form requerrant une signature et détaillant le plan de commandites i3? ainsi que la facture?

**Comment by Res260** [comment]
@MAGNUM81 message envoyé?

**Comment by MAGNUM81** [comment]
Un draft d'accord de commandite a été créé. Lien ici : https://docs.google.com/document/d/1Wdl4pe_GCOsCMKEbqCM-3kzq0SDAx6stfZUS68faOg0/edit

**Comment by MAGNUM81** [comment]
Et Message envoyé. Sans documents sauf un lien vers le plan de commandite actuel.

**Comment by MAGNUM81** [comment]
Facture et accord de commandite envoyés. Waiting for Accord signé

**Comment by Res260** [comment]
Accord signé.
