### ISSUE TITLE
Photo du CE au complet avec banner 😋

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#144]

**Comment by Res260** [comment]
@Blond11516 Pourrais tu faire un tsi post fb pour présenter le CE pis pas oublier jo xx

**Comment by Blond11516** [comment]
Will do. Est-ce qu'il faut que je mette la photo ailleurs aussi? (site ou
whatever)

**Comment by Res260** [comment]
Genre sur Google Photos de jdis

--Émilio

**Comment by Blond11516** [comment]
La photo est ajoutée à l'album et post fait: https://www.facebook.com/JDISherbrooke/photos/a.1002551816478097/2099354516797816/?type=3&theater
