### ISSUE TITLE
Déposer l'argent non utilisé pour remboursement hackfest

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#148]
220$, @Sytten va falloir tu m'expliques comment faire

**Comment by Sytten** [comment]
Tu peux faire un chèque au nom de l'AGEG, je vais m'occuper de remplir la demande

**Comment by Res260** [comment]
finalement j'ai transfer le cash à @Sytten et il fera le dépôt

**Comment by Res260** [comment]
120$

**Comment by Res260** [comment]
C'est déposé ? @Sytten

**Comment by Sytten** [comment]
Ha non fuck j'ai oublié mes chèques

**Comment by Sytten** [comment]
Sera fait lundi
