### ISSUE TITLE
Portes ouvertes

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#149]

**Comment by ArcticWalrus** [comment]
Est-ce qu'il faut préparer quelque chose pour les portes ouvertes?

**Comment by Sytten** [comment]
Idéalement une présentation interactive ça serait nice, on va probablement avoir un projecteur.

**Comment by Res260** [comment]
@Sytten Peux tu mettre les infos ici stp

**Comment by Res260** [comment]
Done c'était ben chill, though pas TANT de monde que ça
