### ISSUE TITLE
Organiser une intégration pour les nouveaux en science et génie info

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#15]
C'est un peu far-fetched, mais j'ai cette idée-là depuis un moment.

Je pense que les JDIS devraient organiser une intégration pour les nouveaux étudiants en informatique. Je parle d'une intégration "officielle" dans le sens qu'on dit aux intégrés que c'est une activité faisant parti de leurs intégrations au même point que ceux organisé par leurs cohortes.

C'est-à-dire un genre de CTF généraliste (style puzzle-hero au CSGames) dans lequel on peut intégrer des trucs TRÈS large. La base de la sécurité (pour ceux du DEC), de la programmation, et plein de choses misc.

Ça donnerait de l'exposure au JDIS, les nouveaux pourraient comprendre ce qu'est un jeu informatique, et en plus ils savent maintenant QUI sont les JDIS.

C'est très vague encore dans ma tête, mais j'ai plein de temps libre pour l'organisation. Vous en pensez-quoi?

**Comment by Pourliver** [comment]
Ça serait peut être nice aussi de faire des équipes, et d'avoir un genre de mentor par équipe.

**Comment by Res260** [comment]
Agreed pour faire des équipes, ce genre de défis c'est qqchose d'assez rassembleur imo et une possibilité de créer des liens

**Comment by Res260** [comment]
Jpense aussi que la plateforme de challenge de Puzzle Hero aux CSGames
serait suited pour ça


--Émilio

**Comment by Pourliver** [comment]
Exact, la plateforme des Puzzle Hero était parfaite, et c'est ça que j'ai en tête. Moins on passe de temps sur le site, plus c'est facile de mettre de l'effort sur les challs et l'organisation.

**Comment by Sytten** [comment]
Ouais j'avais essayé de faire ça un peu l'automne passé. Le truc c'est que bien souvent les nouveaux ne savent absolument pas programmer (surtout en génie info), donc ça marche plus ou moins bien. Je crois que si on veut faire un event comme ça, il faut y aller plus large et faire des défis qui sont bien pour toute la communauté.
Pour la plateforme, on peut aussi utiliser celle des sélections des cs games si on l'améliore un peu.

**Comment by Sytten** [comment]
Je peux essayer de voir si je peux avoir accès, normalement elle est pas open source.

**Comment by Res260** [comment]
C'est quoi le nom de la plateforme?


--Émilio

**Comment by Pourliver** [comment]
Le voici!

https://github.com/csgames/mission_board

**Comment by Res260** [comment]
Looks open enough for me


--Émilio

**Comment by Res260** [comment]
Jviens de mettre 2e CE comme milestone pour qu'on en jase lors du prochain CE

**Comment by Sytten** [comment]
Ouais l'intro aux compe c'était genre juste reprendre un ancien défi IA et aider le monde so ça serait mieux notre nouvelle idée

**Comment by Res260** [comment]
Also à méditer: Trouver un nom cool pour ça

**Comment by Pourliver** [comment]
Pas tant besoin d'un nom cool si on fait juste inclure ça dans l'horaire d'intégration de chaques cohortes IMO. Ce qui est selon moi le but pour que ça soit une vrai activité d'intégration, sinon personne (ou presque) va venir.

**Comment by Res260** [comment]
Proposition si on fait un CTF-like challenge: Donner toutes les ressources nécessaires pour résoudre le challenge dans les descriptions. Ça permet de faire des challenges un peu plus durs (donc plus large) et de baisser la barrière d'entrée.

**Comment by Res260** [comment]
Par exemple, pour la feuille imprimée qu'on a fait au NSec: dire de rechercher "printer steganography" or something like that

**Comment by Pourliver** [comment]
Oui j'suis d'accord à l'idée d'avoir un truc facile d'approche, semblable à ce qu'on retrouve sur Root-Me (à part le shitty UI)

**Comment by Res260** [comment]
@ArcticWalrus Est-ce qu'on a des news du comité organisateur de Génie?

**Comment by Res260** [comment]
Update: ça s'appelle PadawanCTF, c'est le 1er septembre 13:00 à 18:00. Invitation envoyée, manque juste courriel à génie. Challenges en construction par plusieurs personnes.

**Comment by Sytten** [comment]
@Res260 Update et ferme l'issue pls

**Comment by Res260** [comment]
Update: 20 participants environ, le monde a apprécié, juste 3 de génie, faut trouver une façon de pousser plus l'événement. Suggestion: faire ça une semaine plus tard?
