### ISSUE TITLE
Commandite : Contacter Genetec

### ISSUE THREAD

**Issue by MAGNUM81** [JDIS/Organisation#153]
Établir la communication avec Genetec (en particulier la branche Sherbrooke) et essayer d'aller chercher une bonne commandite.

**Comment by MAGNUM81** [comment]
Contact établi avec Stéphanie, responsable des relations universitaires.

**Comment by MAGNUM81** [comment]
Selon notre contact, ils ne sont pas prêts à commanditer à cause de tous les events qui s'en viennent.
Cela dit, ils seraient peut-être partants pour participer aux JDIS Academy De quelle manière? tbd

**Comment by MAGNUM81** [comment]
L'équipe de sherbrooke voudrait faire un workshop en F# ou sur l'encodage/décodage de vidéo.

**Comment by Res260** [comment]
hhmmm tu proposes quelque chose en particulier money-wise?

**Comment by MAGNUM81** [comment]
Aucune idée pour vrai... Ya tu deja eu des arrangements pour les midis-conférences? On pourrait se baser la dessus

**Comment by Res260** [comment]
Nope never

**Comment by MAGNUM81** [comment]
Ok well j'pourrais leur demander gentiment de payer dla pizz mais c'est pas de l'argent ça.

**Comment by Res260** [comment]
Faut recontacter genetec à la session d'été
