### ISSUE TITLE
Clarifier notre stance sur les midi-conférences

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#155]
- Limiter aux sponsors, l'écrire dans le guide JDIS

**Comment by MAGNUM81** [comment]
Seulement les sponsors i3+ auront l'opportunité d'effectuer un midi-conférence... Garantie? Au moins 1 au cours de la commandite(1 an)? Seulement 1?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Res260** [comment]
Au moins un s'ils le veulent et pas plus d'un par session imo

--Émilio

**Comment by Res260** [comment]
Il faudra documenter ce changement dans le guide JDIS.

**Comment by Res260** [comment]
Done pour le guide, voir #140 pour le plan de commandites
