### ISSUE TITLE
Participation à la CQI

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#156]
La CQI 2020 aura une compétition de génie logiciel, il serait nice si une team issue de JDIS participe.
Upside: 
- c'est une compé d'info
- pourrait attirer du monde de génie vers jdis

Downside: 
- enlève de l'impartialité à JDIS
- seulement génie peut participer

**Comment by MAGNUM81** [comment]
Je crois que JDIS est en position de promouvoir ce type d'événement. Qu'ils soient en génie ou en info, les étudiants sont toujours contents d'avoir une team et se faire rembourser une partie de leur billet

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Blond11516** [comment]
Je pense aussi que c'est une bonne idée, c'est pas la fin du monde que ce soit génie only. Et de toute façon j'pense qu'on est déjà assez connus/populaires en sciences, on peut se permettre d'aller chercher quelques points en génie.

Ça aide aussi à faire connaître JDIS et l'UdeS, ce qui est positif pour tout le monde.

**Comment by Res260** [comment]
Not happening unless on se fait poker directement
