### ISSUE TITLE
iHack 2019

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#158]
Patrick du Hackfest m'a poke pour le iHack 2019: 
![image](https://user-images.githubusercontent.com/14599855/51939093-a46e9a80-23dc-11e9-9418-6f36ae42ec17.png)

**Comment by Res260** [comment]
S'enligne pour le 15 juin. Patrick m'a dit que qqun du cégep de sherbrooke voulait pt host, je serai mis en contact prochainement si c'est toujours le cas.

**Comment by Pourliver** [comment]
C'est ben weird qu'il change de gang pour host soudainement tho. Dans un sens, on a l'expérience de l'avoir déjà fait et ça c'est super bien passé :thinking:

**Comment by Res260** [comment]
Convo avec: 
![image](https://user-images.githubusercontent.com/14599855/52256193-cc319700-28e3-11e9-8b9e-f0505930799e.png)

**Comment by Res260** [comment]
Date: samedi 15 juin

**Comment by Res260** [comment]
Formule semblable à l'été passée

**Comment by Res260** [comment]
Done c'était ben sick on a eu environ 40 personnes
