### ISSUE TITLE
CSGames: Faire un guide du participant

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#160]
S'inspirer de l'année passée

**Comment by AntoineTheb** [comment]
Guide 2019: https://docs.google.com/document/d/1P7lCsR2gLN9lQHqj3HcsaKRQ9M-58iV6dp9LvoCr29w/edit#

**Comment by AntoineTheb** [comment]
@Res260 Devrait être complet, mis à part le thème. #97

**Comment by Res260** [comment]
Fait en envoyé
