### ISSUE TITLE
JDIS Academy #4: Reverse Engineering

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#161]
5 février, tout est à faire

**Comment by Blond11516** [comment]
C'est qui qui le présentait celui-là déjà?

**Comment by Res260** [comment]
C'est maxC, je t'ai mis assigned pour la partie comm I guess

--Émilio

**Comment by Blond11516** [comment]
https://www.facebook.com/events/2232538390295914/

**Comment by Pourliver** [comment]
Tout est prêt pour demain! J'ai des bons challenges de fait, et un gros accent sur l'aspect pratique!

**Comment by Res260** [comment]
14 personnes, c'était ben cool hihi
