### ISSUE TITLE
Acheter un/des pointeurs laser pour les midi-conférences

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#163]
Tout le monde pointe avec son doigt c'est lame 😋 

Pis jpense pas c'est ben cher

**Comment by Res260** [comment]
@Sytten News?

**Comment by Res260** [comment]
@Sytten ?

**Comment by Sytten** [comment]
Je vais regarder chez mes parents en fin de semaine

**Comment by Res260** [comment]
on en a déjà un au local, j'ai récupéré des batteries de mon contact de la coalition 👀
