### ISSUE TITLE
Midi-Conférence #2: Félix Vigneault

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#166]
Date: 20 février

Titre: Introduction au design en programmation fonctionnelle

Description:

Vous êtes un habitué des langages de programmation orientée objet? Vous avez une petite idée de ce qu'est la programmation fonctionnelle, mais ce n'est pas encore clair comment vous pourriez construire un programme complexe en fonctionnel? Cette présentation fera une petite étude de cas sur les différences entre la programmation OO et fonctionnelle à l'aide de C# et de OCaml. On parlera de design et d'architecture, en particulier sur les façons de construire des types riches à l'aide de l'héritage, la composition et les types algébriques de données. Aucune connaissance préalable obligatoire, mais la présentation est adressée à un public technique ayant de l'expérience en programmation orientée objet.

Note: No pizz unfortunately hihi

@jolafreniere : Faire l'event et programmer la publication pour le 6 février prochain :)

**Comment by Blond11516** [comment]
https://www.facebook.com/events/596795320761322/

**Comment by Res260** [comment]
Fuck j'ai mal copié le titre c'est programmation fonctionnelle @Blond11516 sry :'( Also va falloir que @jolafreniere  confirme pour le local

**Comment by Blond11516** [comment]
All right j'vais fix. Le local je sais, j'avais du temps so j'voulais clear ça de ma liste :p

**Comment by Blond11516** [comment]
Est-ce que "Midi-conférence JDIS: Le design en programmation fonctionnelle" ça fait comme titre? "Introduction au design" c'est trop long pour Facebook...

**Comment by Res260** [comment]
Yeah c'est chill

**Comment by jolafreniere** [comment]
D7-3021 Réservé

**Comment by Res260** [comment]
@jolafreniere @Blond11516 Le midi-conférence est déplacé au 20 février. Il va falloir re-réserver le local et refaire l'image d'event

**Comment by Blond11516** [comment]
L'event est modifié. La publication est programmée pour le 13 à 11h30.

**Comment by jolafreniere** [comment]
Le local est réservé pour le 20 (d7-3021)

**Comment by Res260** [comment]
22 personnes, nice stream tbh https://youtu.be/ZeV-hwMPoTk?t=428
