### ISSUE TITLE
Retravailler le plan de commandites

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#17]
## Ce qu'on a actuellement:

- i3
    - **250-499$**
    - Logo de taille régulière sur notre site web, nos réseaux sociaux et notre étendard
    - Distribution de matériel promotionnel

- i5
    - **500-999$**
    - Tous les avantages des plans précédents
    - Logo de grande taille sur notre site web, nos réseaux sociaux et notre étendard
    - Sponsor d’une compétition

- i7
    - **1000-1999$**
    - Tous les avantages des plans précédents
    - Promotion d’activité corporative avec JDIS
    - Sponsor des vidéos JDIS (YouTube)

- Xeon
    - **2000$+**
    - Tous les avantages des plans précédents
    - Sponsor de la conférence JDIS

Que proposez-vous qu'on change?

Perso:
- Je retirerais le range de prix pour mettre un prix fixe par catégorie.
- Je mettrais à i5 mention sur nos posts Facebook
- Clarifier "Sponsor d'une compétition"
- Linker JDISConf
- Rendre Xeon plus intéressant?
- "Sponsor des vidéos JDIS (YouTube)" RIP

**Comment by Res260** [comment]
But les commanditaires de jdisconf c'est pas séparé?

**Comment by Sytten** [comment]
Oui mais c'était une façon d'attirer une grosse commandite en incluant une autre commandite, mais ça marche pas :s

**Comment by Res260** [comment]
Est-ce que qqun a le document du plan de commandites?

**Comment by Res260** [comment]
> Nous considérons comme membres tous les
> étudiants inscrits à notre groupe privé Facebook.
> Ceux-ci viennent majoritairement des Facultés de
> sciences et de génie. Sur les deux cents membres
> dénombrés, nous en considérons
> approximativement une cinquantaine comme
> étant actifs.

We gotta retravailler ça

**Comment by Res260** [comment]
> De plus, une
> fois par année, nous organisons une conférence
> d’envergure d’une journée avec une assistance de
> près d’une centaine de passionnés sur un thème
> d’actualité dans l’industrie.

On était pas dépassé 100 cette année?

**Comment by Res260** [comment]
Pis @Sytten es-tu capable de me breakdown le budget de JDIS en % dans ces catégories:

- Compétitions informatique
- Conférences hors sherby
- Jdisconf
- Tout le reste à sherb (midi-conférence, ateliers, compétitions amicales n shit)
- Misc (genre site web n shit)

**Comment by Res260** [comment]
Actuellement, dans le plan de commandite, y'a une page complète (33%) dédiée à parler des compétitions/délégations pis jme demande si ça prend pas trop de place dans le plan, parce que jme demande si c'est ce qui est le plus important pour les commanditaires potentiels.

**Comment by FelixMartel** [comment]
@Sytten ou juste leur donner acces au drive

**Comment by Sytten** [comment]
J'ai donner accès au drive, mais pour le budget on pourrait se faire un petit call que je texplique comme il fonctionne @Res260 
Je suis d'accord avec tes observations!

**Comment by Res260** [comment]
Alrite tho je sais pas quand on aura une dispo commune hahaha

**Comment by Res260** [comment]
Sinon êtes-vous d'accord avec le retrait des range de prix ou vous préférez les garder?

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/39066042-bc0d636c-44a1-11e8-9ec9-34f0d7f4999b.png)

🤔

**Comment by Res260** [comment]
So dans le fond y'a tu qqun qui a d'autres idées? @FelixMartel @maximevaillancourt @Pourliver @Wingjam

**Comment by urospet** [comment]
https://docs.google.com/spreadsheets/d/16bgHA7vEaG_-HpZKGjhCduq95ThrqaNojzfve22j__4/edit?usp=sharing

**Comment by urospet** [comment]
C'est le plan de commandite retravaillé, hésitait pas à mettre des commentaires dans le document ou ici, c'est une deuxième version suite à vos premiers commentaires

**Comment by maximevaillancourt** [comment]
J'ai corrigé quelques coquilles dans le contenu, et légèrement modifié l'aspect visuel du document (utilisation du vert JDIS `#119E5D` et amélioration de l'en-tête).

**Comment by maximevaillancourt** [comment]
Personnellement, j'aime que le document soit _straight to the point_, mais j'ai l'impression que les départements de RH et de marketing des entreprises qui vont consulter ce document-là vont peut-être préférer avoir quelques photos ou un peu de contexte sur JDIS avant de lire le plan de commandite, qui peut paraître un peu froid et direct.

Est-ce qu'on a un autre document dans lequel on parle de l'histoire de JDIS, et qu'on pourrait fournir aux entreprises en même temps que le plan de commandite? Sinon, pourquoi ne pas intégrer le tableau des forfaits dans un document où on explique notre histoire et nos objectifs futurs avec quelques photos de nos événements? :thinking:

**Comment by Res260** [comment]
Jpas mal sûr qu'on prévoyait pas se débarrasser du document qu'on avait

**Comment by urospet** [comment]
[PlanDeCommandite-JDIS-2018 .pdf](https://github.com/JDIS/Organisation/files/2065037/PlanDeCommandite-JDIS-2018.pdf)

**Comment by urospet** [comment]
Devrait être la version finale ça
