### ISSUE TITLE
Commandite : LogMeIn

### ISSUE THREAD

**Issue by MAGNUM81** [JDIS/Organisation#170]
Établir le contact avec l'aide d'Ismael. La personne à contacter serait un certain Julien Beaupré.

**Comment by MAGNUM81** [comment]
Le plan de commandite est prêt

**Comment by tihbe** [comment]
Email envoyé, en attente d'une réponse

**Comment by Res260** [comment]
pas de réponse, ismael va relancer

**Comment by Res260** [comment]
Des nouvelles?

**Comment by tihbe** [comment]
J'ai relancé jeudi dernier, toujours rien

**Comment by Res260** [comment]
Bon je ferme, on réouvre si on a qqchose de nouveau
