### ISSUE TITLE
Délégation Northsec 2018

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#18]
- [x] Remboursement des billets
- [x] Organisation des transports
- [x] Organisation de l'hébergement
- [x] Rencontre préparatoire

**Comment by Res260** [comment]
Organisation de l'hébergement in progress

**Comment by Res260** [comment]
Pour la rencontre préparatoire jvais probablement faire un tsi post aujourd'hui pour le lundi 7 mai.

**Comment by Pourliver** [comment]
En quoi consiste la recontre  préparatoire? Un peu comme le "pré csgames"?

**Comment by Res260** [comment]
Moi jpensais que juste faire le ctf101 avec le monde serait suffisant :)

**Comment by Pourliver** [comment]
Oh celui du montréhack, good!

**Comment by Pourliver** [comment]
Wait, moi je donne l'intro à la sécu le 14 tho. C'est pas un peu mixed up?

**Comment by Res260** [comment]
I mean kinda un tsi peu, mais ton affaire va actually être organisée et
publicisée, pas le 7


--Émilio

**Comment by Res260** [comment]
Transport organisé

**Comment by Sytten** [comment]
Je crois que l'hebergement est correct?

**Comment by Sytten** [comment]
Le remboursement est en cours

**Comment by Res260** [comment]
oui hébergement ok

**Comment by Res260** [comment]
on close?
