### ISSUE TITLE
Suivi du Fonds insitutionnel Hackfest 2018

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#183]
Dernier commentaire: `Formulaire envoyé, en attente de réponse. 190108`
Je vais vérifier avec l'AGEG pour savoir si c'est rentré, mais je pense pas.

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/52605534-48c0fa00-2e3d-11e9-8177-dcd9f2783eae.png)

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/52605541-4fe80800-2e3d-11e9-8d51-9667e9379796.png)

**Comment by Res260** [comment]
Ça j'ai reçu, ball on their camp

**Comment by Res260** [comment]
Still va falloir vérifier si c'est rentré avant que je les repoke

**Comment by Res260** [comment]
On devrait avoir des news cette semaine

**Comment by Res260** [comment]
Bonjour Emilio,

 

Nous avons effectué votre demande de remboursement au Service des ressources financières pour votre projet « Hackfest 2018 » (FAEÉ 2018-2019/49). Le versement devrait parvenir à l’AGEG, pour le groupe JDIS comme demandé, dans un délai d’environ 15 jours ouvrables.

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/54638505-9266bb00-4a61-11e9-9177-d8e3435bca31.png)
