### ISSUE TITLE
Effectuer demandes de fonds

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#184]
- [x] Fonds institutionnel
- [x] Département d'informatique
- [ ] Département de génie informatique (je suis pas trop à l'aise comme on a pas beaucoup d'étudiants en Génie)
- [x] AGES

**Comment by Res260** [comment]
AGES

**Comment by Sytten** [comment]
Non c'est pas un événement à l'université

**Comment by Res260** [comment]
L'année passée on a pas eu 250$ d'eux??

**Comment by Sytten** [comment]
Pas pour les CS Games c'est certain

**Comment by Res260** [comment]
jpensais c'était pour ça 🤔

**Comment by Res260** [comment]
Ça qualifie en tk
![image](https://user-images.githubusercontent.com/14599855/52647725-400b0b00-2eb3-11e9-96f1-af18f4d2d127.png)

**Comment by Sytten** [comment]
Normalement le departement a besoin d'une facture pour effectuer le paiement, à voir

**Comment by Res260** [comment]
we good

**Comment by Sytten** [comment]
Faudrait que fasse le retour though

**Comment by Res260** [comment]
?

**Comment by Sytten** [comment]
pour le fonds inst.
