### ISSUE TITLE
Concours pour le logo

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#185]
Je propose qu'on fasse un concours pour changer notre logo. Je trouve qu'il serait temps et il faudrait le faire avant les cartes d'affaires et la pancarte du local. Thoughts?

**Comment by Sytten** [comment]
@JDIS/ce please comment

**Comment by Blond11516** [comment]
Bonne idée. Est-ce qu'on donne un prix ou juste du fame?

**Comment by DrPandemic** [comment]
Faire un concours a le downside que s'il n'y rien que tu aimes, tu es pogné avec ça.

**Comment by Res260** [comment]
Si on fait un concours y faut donner un prix tbh

**Comment by ArcticWalrus** [comment]
Qu'est-ce qu'on peut faire comme prix? L'argent?

**Comment by Res260** [comment]
ouais pretty much

**Comment by Sytten** [comment]
Sinon comme proposé sur slack on peut le crowdsource, comme ça on peut juste le reject si on aime pas

**Comment by Res260** [comment]
Unsure de la différence?

**Comment by Sytten** [comment]
Mettons https://www.designcrowd.com/, tu donne un montant pis ya du monde qui bet dessus

**Comment by Res260** [comment]
Personne ne semble vouloir s'en occuper, je fermerais
