### ISSUE TITLE
Envoyer les CVs de la délé CSGames aux sponsors

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#186]

**Comment by MAGNUM81** [comment]
Où sont les CVs? J'ai cru voir qqpart qu'ils avaient été récupérés...

**Comment by Res260** [comment]
Dans Form/collectedecv/*/csgames2019

**Comment by Res260** [comment]
Référer au guide jdis pour un template de message à envoyer. N'envoyer qu'à nos sponsors xeon

**Comment by MAGNUM81** [comment]
Courriel envoyé

**Comment by MAGNUM81** [comment]
I guess que je vais attendre un accusé de réception avant de close l'issue

**Comment by Res260** [comment]
no need tu peux fermer

--Émilio
