### ISSUE TITLE
Faire un post pour le groupe membres jdis

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#188]

**Comment by Blond11516** [comment]
https://www.facebook.com/JDISherbrooke/posts/2117112541688680?__xts__%5B0%5D=68.ARA6-40RqD0lrpMytoW6dETYTQaBRJ77T1Xka6m1OQjOCJDWFYKJ5SLpX19Y0ILUMK7Z-Al3_FmjF-OgKEnLAuqT9XWnJDM_-mdlp7AoAnlwvm-kkpAzMc7YO4BUkQidE67ksYEG8zG3vHAkLIqLq-uOiULMF4Voi0bfIT9lNmI1ahfv-eQtNN_Y0fbTfwYTdRNg8QHJIwCk1LZ2iKHRf2L1cBigCues03K6LIanicAkxVH2HQPFfhtPz4ZedrQ8onYF43YxEYif9QawLPYXfxVoFp_Z9BiE05NJ5ExOouD6spnsq07-T75Ug-RPsU6xJsaoPQo1xtZLauzx4-GNSg1MCQ&__tn__=-R
