### ISSUE TITLE
Recevoir CyberEco pour une présentation

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#190]
Jme suis fait poke par une amie qui travaille pour [CyberEco](https://cybereco.ca/), un OSBL qui a pour sensibiliser les étudiant-e-s en informatique à la cybersécurité et les options de carrière.

Elle voudrait faire une présentation le midi (probablement avec pizza) d'environ 45 mins.

Pas de date, ça serait à voir.

J'en parle en CE lundi.

**Comment by Res260** [comment]
Accepté, ça serait probablement un jeudi midi pour les accommoder. J'attend la confirmation pour le 11 avril.

**Comment by Res260** [comment]
Confirmation reçue, jcheck ça plus tard

**Comment by Blond11516** [comment]
https://www.facebook.com/events/300680907293768/

Brouillon de l'event fait, je laisse @Res260 double check et publish

**Comment by Res260** [comment]
37 personnes, c'était ben cool xx
Lien vers la présentation: https://www.youtube.com/watch?v=sglgWYJKd7k
