### ISSUE TITLE
JDIS Academy en génie

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#191]
Ça devrait être une semaine sur deux. Je propose le C1-3125 comme local c'est bon pour ce genre de présentations.

**Comment by Sytten** [comment]
Je peux réserver le local, mais je crois pas que ça soit nécessaire ya pas de cours le soir en génie

**Comment by Justin2997** [comment]
Peut-être qui aurais quelque chose à faire avec le salon de l'AGEG aussi, genre tu pourrais ouvrir des tables mais l'ambiance est décontracter avec les divans.

**Comment by Res260** [comment]
@Justin2997  Seul problème que je vois avec ça c'est que ça va pas bien pour présenter, surtout quand y'a d'autre monde autour

**Comment by Justin2997** [comment]
@Res260 Si je comprendre c'est le soir et la salle ce ferme. Moi je fesais des formations de robotique et c'était vraiment bien. Surtoute que si tu veux te commander de la bouf c'est bien organisé.

**Comment by Res260** [comment]
Could be a nice idea à considérer plus tard, mais for now je préfèrerais quelque chose de plus standard/moins compliqué pour qu'on mette ça sur pied rapidement :) 

Accepté en CE
