### ISSUE TITLE
JDIS Academy aux deux semaines?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#192]
Est-ce que c'est trop fréquent à chaque semaine?

**Comment by ArcticWalrus** [comment]
Je crois que c'est beaucoup mais est-ce que notre objectif c'est d'avoir tout le monde à chaque fois? Le problème avec le fait de les avoir aux 2 semaines c'est que les gens commencent à se demander c'est quelle semaine qu'il va en avoir.

**Comment by ArcticWalrus** [comment]
Je crois que le fait d'avoir le midi conférence et le jdis academy dans le même post ça a fait un mûr de text aussi

**Comment by Res260** [comment]
Accepté en CE
