### ISSUE TITLE
Faire la demande de subvention au recsus pour JDISConf 

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#193]
À faire avant de mois d'aout.

**Comment by Sytten** [comment]
Hein? pour 2019?

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/53203080-2a55be00-35f6-11e9-9fb0-4479b2856b15.png)

**Comment by Res260** [comment]
rouvrir un issue if important
