### ISSUE TITLE
Actually utiliser le LinkedIn?

### ISSUE THREAD

**Issue by MAGNUM81** [JDIS/Organisation#195]
J'ai pensé à ça pendant mon 2h30 de commutation hebdomadaire... Si JDIS avait une page LinkedIn...

1. Ça serait dope, 
2. Ça nous apporterait plus de visibilité sur les réseaux sociaux,
3. Ça augmenterait sûrement la crédibilité de JDIS et de ses membres auprès des entreprises...

On jase là!

**Comment by Res260** [comment]
On a déjà un compte linked in, mais on l'utilise pas :p

**Comment by AntoineTheb** [comment]
https://www.linkedin.com/company/jdis/

**Comment by AntoineTheb** [comment]
Nouvel issue: Actually utiliser le linkedin ?

**Comment by Res260** [comment]
Est-ce qu'un mirror de posts fb comme avec twitter marcherait lmao

**Comment by MAGNUM81** [comment]
Mouais jsp ça serait plus orienté vers les entreprises que les personnes qui suivent JDIS. Ça pourrait ressembler à du  "Advertisement" pour jdis aupres des entreprises

**Comment by Res260** [comment]
mentionner aux sponsors qu'on a un linked in xd

**Comment by Res260** [comment]
rip
