### ISSUE TITLE
documenter la procédure pour streamer sur le guide jdis

### ISSUE THREAD

**Issue by jolafreniere** [JDIS/Organisation#199]

**Comment by Res260** [comment]
En fait ça serait plus "documenter la procédure pour streamer sur le guide jdis"

**Comment by Res260** [comment]
https://github.com/JDIS/guide-jdis/wiki/Proc%C3%A9dure-pour-streamer-une-pr%C3%A9sentation va falloir que quelqu'un la battle-test
