### ISSUE TITLE
Monter compétition IA 2018

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#20]
- [x] Déterminer la date : 14 juillet 2018
- [x] Trouver le jeu: aigar.io
- [x] Monter la plateforme
- [x] Réservation de la salle
- [x] Achat pizza et boisson 
- [x] Avoir système de son + micro (voir AGES?)
- [x] Avoir des fils ethernet et switches en masse
- [x] Avoir deux projecteurs

**Comment by Res260** [comment]
C'était assigné à Malcom ça right?

**Comment by Sytten** [comment]
Nah ça c'est on me

**Comment by Sytten** [comment]
Dicussion: on essaye de voir si les autres unis sont intéressées.

**Comment by Res260** [comment]
Update: ouvert à tous: https://www.facebook.com/events/382735435545024/
