### ISSUE TITLE
JDIS Academy #8: Genetec

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#201]
Date 26 mars, à confirmer avec Genetec pour le reste

**Comment by MAGNUM81** [comment]
Ils veulent probablement le faire en mai finalement. Je leur ai dit que notre comité allait être très différent et donc qu'on peut pas confirmer de date.

**Comment by Res260** [comment]
@MAGNUM81 lol on a pas eu de CE, ouain tu peux leur dire de nous recontacter début mai I guess

**Comment by Res260** [comment]
rip xd
