### ISSUE TITLE
Partager technodrink du 20 mars

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#203]
Cuz il est dans les bureaux de sherweb

**Comment by AntoineTheb** [comment]
Faut pas oublier de dire aux gens de s'inscrire aussi. I feel like c'est pas assez promu d'hab

**Comment by Blond11516** [comment]
https://www.facebook.com/JDISherbrooke/posts/2153515754715025?__xts__[0]=68.ARA64qNs3R4slW_G9HOw6Za37ajNpA8iFPmpgtkGjzxD2DzIuRGGQtrhVveDec9VVziCRpaXR8Xf2wZ21WHOec6IbE5Xvq2jQUj8vReXdyMSRj2bKq_1tjECSXJY7lXK5PDlOpvSlv2s9ca201OA91Ye4ClUsNjz0UgqrwSVI6X8sxPRYFDDTYC29XoL67JuSJz5wAfIRISruTTNjnPwoZPGBghnPELAt1Zzb5gfzz_YyAi45tbo8U78mu53STlkrbee6m45m02RwYUPZrsPuzVBTG_qIPXoactEalHQNaWi_yZmuZnDruxGRkIg5IizWrkJnUskS9O8iuHuoS-mJJlHfg&__tn__=-R
