### ISSUE TITLE
Merge JDISConf et Cabane.io

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#204]
J'ai parlé avec Marc-Antoine Veilleux de Coveo. Il veut organiser un équivalent de la conférence https://cabane.io à Sherbrooke. Je crois qu'on devrait merge les efforts et faire un truc ensemble. Ça permettrait d'atteindre un plus grand public et de faire grossir l'événement.

**Comment by Sytten** [comment]
Je crois aussi qu'on commence à épuiser le concept actuel et ça ferait du bien de changer! On peut toujours revenir si on aime pas ça.

**Comment by Res260** [comment]
À jaser lors du prochain CE?

**Comment by Res260** [comment]
Pas mal fait, Cabane.io sherbrooke le 26 octobre prochain
