### ISSUE TITLE
post fb cs games

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#205]
Pas en ordre:
- Remercier nos sponsors
- Mentionner tous nos prix et ceux qui les ont gagnés
- Photo d'équipe (celle de mcgill, pt mentionner pourquoi on est habillé en mcgill xd)
- Féliciter @dciets pour la victoire 
- Remercier le CO de poly

**Comment by Blond11516** [comment]
Photo des trophées?

**Comment by Res260** [comment]
on a tu ça

--Émilio

**Comment by Blond11516** [comment]
J'peux en prendre une

**Comment by Res260** [comment]
kk

--Émilio

**Comment by Blond11516** [comment]
Brouillon : https://www.facebook.com/842249629174984/posts/2172015692865031/
