### ISSUE TITLE
renouveler la commandite de Coveo avec JDIS games

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#207]
commandite expire en juillet, faudrait leur proposer de renouveler comme l'année passée avec JDIS Games

**Comment by MAGNUM81** [comment]
courriel envoyé à Ezmie Bouchard - RH <ebouchard2@coveo.com>

**Comment by MAGNUM81** [comment]
Réponse: 
Merci de nous contacter!

Serait-il possible de nous fournir un programme de partenariat et un peu plus d’information sur l’événement, SVP?

**Comment by Res260** [comment]
On parle de renouveller coveo comme sponsors régulier, donc envoie leur le
plan 2019. Dis leur que l'année passée, ils ont pris xeon (2000$) et qu'à
cause de ça on les a mis commanditaires principaux de JDISGames et qu'on
peut faire la même chose que l'année passée (c'est pas qqchose qui est dans
le plan de commandites)

Tu peux lui mentionner que l'année passée notre contact pour ça était
Marie-Êve Drouin.

Pour JDIS Games, c'est une compétition d'intelligence artificielle
semblable à celle qu'ils organisent (Coveo Blitz). L'année passée, c'était
en team de 2 et on a accueilli environ 60 personnes de 6-7 écoles
différentes, y'avait un chandail d'événement avec logos de sponsors et le
monde devait coder un bot qui joue à une version modifiée d'agar.io. Cette
année, le jeu sera une version modifiée de PacMan, on est encore à finir
les détails de la compé. On avait limité les inscriptions à 60 personnes à
cause qu'on voulait pas scaler trop vite, c'est possible qu'on accueille
plus de monde cette année.

--Émilio

**Comment by Res260** [comment]
Coveo renouvelle Xeon 🎉

**Comment by MAGNUM81** [comment]
Accord de commandite envoyé. Les détails financiers seront réglés en juin.

**Comment by Res260** [comment]
In progress.

**Comment by Res260** [comment]
Done, en attente de la facture
