### ISSUE TITLE
Considérer l'achat d'un micro?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#210]

**Comment by Sytten** [comment]
#268

**Comment by Sytten** [comment]
Demande #267

**Comment by Res260** [comment]
quoi?

**Comment by Goglu023** [comment]
https://www.amazon.ca/Samson-Wireless-Microphone-System-SWXPD2BLM8/dp/B07HPRZBKC/ref=sr_1_1?keywords=Samson+xpd2&qid=1571924949&s=musical-instruments&sr=1-1-catcorr
