### ISSUE TITLE
Midi-conférence E2018

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#22]
- [ ] Réservation du local dans le D7 (mercredi)
- [ ] Contacter les sponsors et professeurs
- [ ] Publicité

**Comment by Res260** [comment]
Est-ce que c'était assigné à quelqu'un?

**Comment by Sytten** [comment]
Oui mais j'ai pas son github

**Comment by ArcticWalrus** [comment]
Deux personnes ont confirmé qu'ils serait intéressés (Coveo, Sherweb). Il faut maintenant contacter des chargés de cours et d'autres compagnies. J'attend de voir leur date qu'ils me proposent

**Comment by ArcticWalrus** [comment]
Contact à Sherweb de retour vendredi.
J'attend la confirmation de Coveo pour savoir s'ils veulent faire un midi conférence cet été finalement ou seulement à l'automne

**Comment by Res260** [comment]
Bilan: 1 midi-conférence :^)
