### ISSUE TITLE
Renouvellement commandite Sherbrooke Innopole

### ISSUE THREAD

**Issue by MAGNUM81** [JDIS/Organisation#220]
point de contact à confirmer : charles@espace-inc.org

**Comment by Res260** [comment]
https://puu.sh/DrmLx/27fc95903e.png

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/57585178-7d7f3480-74b2-11e9-9a47-6ee0946dc6c3.png)

**Comment by Res260** [comment]
Jpas sûr exactement comment m'occuper de ça, faudrait éventuellement documenter cette procédure dans le guide JDIS. En attendant, @Sytten tu pourrais me guider?

**Comment by Res260** [comment]
In progress

**Comment by Sytten** [comment]
Ping moi si ta besoin d'aide

**Comment by Res260** [comment]
done, reçu
