### ISSUE TITLE
Partager le 5@8 sherweb du 21 mai

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#222]
Bonjour,

 

SherWeb organise un 5@7 SherWeb Connect-e : Stages DEV le mardi 21 mai 2019 à nos bureaux de Sherbrooke. L’évènement s’adresse aux étudiants intéressés à réaliser leur prochain stage (automne 2019) chez nous.

 

Il nous serait d’une grande aide si vous pouviez partager l’invitation à tous les étudiants en informatique ainsi qu’à vos contacts et à l'afficher sur l'ensemble de vos réseaux.

 

Pour toute question ou pour plus de précision, n’hésitez pas à me contacter directement.

 

Événement Facebook : https://www.facebook.com/events/279888739397737

Inscription Directement sur Eventbrite :  https://www.eventbrite.ca/e/billets-57-sherwebconnect-e-stages-dev-61030919122?aff=affiliate1

 

Merci d’avance de votre collaboration!

**Comment by Blond11516** [comment]
Est-ce qu'on envoie des courriels ou Facebook seulement?

**Comment by Res260** [comment]
Facebook only

**Comment by Res260** [comment]
Post + membres JDIS mettons

**Comment by Blond11516** [comment]
https://www.facebook.com/JDISherbrooke/posts/2226553304077936?__xts__[0]=68.ARA6Q-zeuc6Z_TED1fvx6-_D3hRPxw5dTsHA-B5aOLbwUkCQp2iUC6Dpv9w4ZbnnRWfdgoXZVL0Okz_Vf2_gjo8JF6PQkGSw7c-ixhuwzM2BWZL_E7d5suvMOPKPw1m1LzPpqt8klZRzIDU3RerQtoHF7TRZ7aSNeHemTPv7rEYmoxj1OsNjQQlfj8OheBt-ds5gLRDaZ80E5k83HdPbMCzeW78jHwGeO1Xaq_tLyNu8-0XRG0O1I2cMVBo0pFStG4IMZOm4iEs6P62h8Vi-3Z32Z9wzN8kDsjG0aXLS2Hse0xaEtwjTnFrLv0dCu7O3Q2y4e2E4qXbNeJriCa-dsMoFmrBZ3GJCNqh2sHwbXOIctB0J2uo8cOQ&__tn__=-R

https://www.facebook.com/groups/jdisherbrooke/permalink/2653892761348561/
