### ISSUE TITLE
Établir une liste des membres de JDIS

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#23]
- [x] Établir une définition d'un membre
- [x] Recueillir les emails des étudiants (et leur faculté)

**Comment by Res260** [comment]
Session ou année?

**Comment by Sytten** [comment]
Année en effet

**Comment by Res260** [comment]
Lors de l'événement de @Pourliver lundi dernier, on a recueilli 23 entries (dont une invalide).

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/40064515-aee9b920-582d-11e8-9e4b-cc430400b1ca.png)

**Comment by Sytten** [comment]
Je vais ajouter une option pour ceux pas a l'uni

**Comment by Res260** [comment]
Y faudrait ajouter les emails du monde qui est venu au nsec à la liste de membres

**Comment by Res260** [comment]
What?


--Émilio

**Comment by Sytten** [comment]
Ben faut nous ajouter, on est membre de jdis :P

**Comment by Res260** [comment]
l'event de formation?


--Émilio

**Comment by AnthonyIleret** [comment]
Emile avec la tablette ça avance ?

**Comment by Res260** [comment]
@Sytten

**Comment by Sytten** [comment]
He I guess? On l'a pas encore utilisé, mais elle devrait marcher.

**Comment by Res260** [comment]
La tienne ou une nouvelle qu'on achète?

**Comment by Sytten** [comment]
La mienne marche, on essayera au prochain midi-conférence

**Comment by Res260** [comment]
On fait quoi du monde qui vient pas de l'uni de Sherbrooke pour la liste de membre (ie compé AI)?

**Comment by Res260** [comment]
D'où ma question, on les ajoute?

**Comment by Res260** [comment]
Liste de membres créée, faut juste penser de la garder à jour à chaque événement. Les étudiants qui ne viennent pas de l'uni sont dans "Étudiant(e) hors de l'université / pas étudiant(e)"
