### ISSUE TITLE
Capes 2.0

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#230]
LEAVING THIS OPEN TANT QU'ON A PAS DES NOUVELLES CAPES FULL SICK

jpense que nos finances nous le permettent cc @Sytten

**Comment by Pourliver** [comment]
#MakeJDISCapedAgain.

**Comment by Res260** [comment]
https://www.ebay.ca/itm/Halloween-Cosplay-Costume-Star-Wars-Women-Men-Jedi-Warrior-Hooded-Cloak-Robe/112566146368?hash=item1a35771540:m:m-scm8bSrYphSU3QzxbHBrw

**Comment by Res260** [comment]
À mettre sur les capes:

- Logo JDIS
- Logo UdeS
- RGB STRIPS (optional)

**Comment by AntoineTheb** [comment]
No way que les RDB strips vont tougher longtemps haha

**Comment by AntoineTheb** [comment]
> https://www.ebay.ca/itm/Halloween-Cosplay-Costume-Star-Wars-Women-Men-Jedi-Warrior-Hooded-Cloak-Robe/112566146368?hash=item1a35771540:m:m-scm8bSrYphSU3QzxbHBrw

https://www.wish.com/product/5a3f3700e723d80927dd1cf2?hide_login_modal=true

Full costume pour 34$ ?!

**Comment by Res260** [comment]
>No way que les RGB strips vont tougher longtemps haha

😡😡😡😡

**Comment by AntoineTheb** [comment]
> > :rage: :rage: :rage: :rage:
:(

Mais les costumes complet ça serait fucking sick tho

**Comment by Res260** [comment]
Y'est écrit 16$ pas 7 pour moi

Pis imo c'est trop lourd tout le costume

**Comment by Res260** [comment]
Done, le logo est un peu bas dans le dos, mais sinon c'est chill
