### ISSUE TITLE
Hackfest: faire le groupe fb et le publiciser

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#232]

**Comment by Res260** [comment]
Faudrait faire ça rapidement, le early bird termine dans 4 jours cette année so on est trop tard pour ça, mais plus tôt on a une approximation du nombre de participants mieux on peut négocier

**Comment by Pourliver** [comment]
Le early bird s'applique pas pour le rabais étudiant si je me souviens bien. On a déjà un prix équivalent (messemble?. Faudrait écrire à Patrick.

**Comment by Res260** [comment]
l'année passée on a pas eu de rabais étudiant, on a eu un rabais pcq on achetais + de 20 billets. Faudrait avoir une bonne idée de cb on en prend avant de contacter, d'où la création du compte fb

**Comment by Pourliver** [comment]
Le groupe est créé.

**Comment by Res260** [comment]
done
