### ISSUE TITLE
Monter une timeline des événements

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#24]
- [ ] Trouver un format lisible et utile
- [ ] Lister les événements (hackathon, sécu, etc.)
- [ ] Lister les dates approximatives pour l'achat des billets

**Comment by Res260** [comment]
C,est sûr qu'il existe déjà un service en ligne pour ça. J'ai pas cherché, mais quelqu'un en connaît un?

**Comment by Res260** [comment]
J'ai oublié quelque chose?
![image](https://user-images.githubusercontent.com/14599855/39656331-0b84e77c-4fcd-11e8-8002-aa20de267bb1.png)

Je pense que c'est également quelque chose, qu'une fois peaufiné, serait intéressant à partager, par exemple sur notre site Web.

**Comment by Res260** [comment]
J'ai actually oublié les dates d'achats de billets tho, mais sans ça c'est cool pareil à montrer à nos potentiels commanditaires

**Comment by Sytten** [comment]
J'aime vraiment la représentation. Est-ce que ya moyen d'export le data dans calendar histoire qu'on refasse pas le travail deux fois?
Je crois qu'on devrait avoir deux timelines, une interne avec les dates d'achat de billets et une externe pour les membres et les commanditaires.

**Comment by Sytten** [comment]
On a d'autres événements que ceux mentionnés, mais ils ne sont pas aussi "fixes". genre les jeux mirego, les jeux genetec, les ateliers git et c++, etc.

**Comment by Res260** [comment]
From my understanding on peut import un CSV pour générer ça.

**Comment by Sytten** [comment]
Je changerais le titre parce qu'on organise pas la moitiés des trucs mentionnés. Sinon GG

**Comment by Res260** [comment]
Ouais j'étais pas sûr si je mettais jeux mirego/genetec

**Comment by Res260** [comment]
À peu près la moitié actually, mais spour ça j'ai écris `(délégation)` :^)

**Comment by Res260** [comment]
organisées et gérées* pt?

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/39657832-d048f510-4fd9-11e8-9771-2aece6324c74.png)

Version 2

**Comment by Res260** [comment]
Je sais pas si on devrais stick avec Vizzlo though, c'est 14$ US pour un mois pour pouvoir remove le watermark.

**Comment by Res260** [comment]
Actually c'est moins gossant quand il est embed:
https://vizzlo.com/embed/res260/3d55318d-0625-4286-b446-cad20d3f4dfc

**Comment by Res260** [comment]
Lié à #1 , je fermerais for now.
