### ISSUE TITLE
Midi-Conférence #3: Bergy

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#242]
27 novembre

**Comment by Blond11516** [comment]
Ça va être Bergy qui va nous parler de son projet de thèse, un nouveau protocole pour l'IoT.

**Comment by Blond11516** [comment]
@p-chatzi 

Titre : Communication entre objets intelligents

Résumé : Les objets capables de communication envahissent tranquillement notre quotidien. Toutefois, leur façon actuelle de communiquer n’est pas toujours optimale. Dans cette présentation, je vais introduire une nouvelle forme de communication basée sur la distance entre les objets. Le protocole de communication ainsi défini sera ensuite illustré dans le contexte d’une intersection routière intelligente.

**Comment by Res260** [comment]
Moins de 10 personnes :(
