### ISSUE TITLE
Application pour la bourse alizée et AIPSA

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#244]
Il s'agit de deux bourses en génie. Comme ça fait un bout qu'on a pas appliqué on a des chances. Mais il faut écrire un gros document donc je vais voir, on peut aller chercher 500 à 1000$.

**Comment by Res260** [comment]
c'est quoi les conditions?

**Comment by Sytten** [comment]
Normalement y faut avoir un genre de projet, mais on a déjà eu de l'argent juste en présentant nos activités. Juste que dernièrement il y a eu beaucoup de nouveaux groupes qui ont priorité dans ce genre de bourses (et c'est ultra chiant remplir la demande)

**Comment by Res260** [comment]
Pas le temps :(
