### ISSUE TITLE
Tour de classe sciences

### ISSUE THREAD

**Issue by Blond11516** [JDIS/Organisation#254]
Faire un tour de classe pour présenter JDIS aux nouveaux (avec et sans arrimage).

Sans arrimage : possibilité de le faire en IFT187 mercredi 8h30 ou jeudi 13h30.
Avec arrimarge : voir avec Mikael Fortin pour le faire en IFT209

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/64269749-7324f280-cf08-11e9-8b2c-a57663209963.png)

**Comment by Res260** [comment]
on passe mercredi 8:30 et 10:30

**Comment by Res260** [comment]
rip mercredi 8:30, y'étaient en lab pis on savait pas

**Comment by Res260** [comment]
done, ctait bien sick
