### ISSUE TITLE
Tour de classe génie

### ISSUE THREAD

**Issue by Blond11516** [JDIS/Organisation#255]
Faire un tour dans un cours des nouveax pour leur présenter JDIS.

**Comment by Sytten** [comment]
Le 12 sept on peut

**Comment by ArcticWalrus** [comment]
@Sytten À quelle heure?
J'ai un cours de projet de 9 à 11 mais je peux me libérer pour faire la tournée avec toi.

**Comment by Res260** [comment]
@Sytten l'a fait
