### ISSUE TITLE
Nouveau logo

### ISSUE THREAD

**Issue by Blond11516** [JDIS/Organisation#256]
Essayer de finir par actually avoir un nouveau logo. Je vais parler à Carl Gauthier pour savoir s'il a le temps/l'envie.

Urgent parce que si on le fait c'est bloquant pour pas mal de trucs.

**Comment by Blond11516** [comment]
Carl ne veut pas le faire finalement, en attente de savoir si on cherche quelqu'un d'autre ou si on laisse tomber.

**Comment by Res260** [comment]
I guess rip? @Sytten

**Comment by Sytten** [comment]
:( Faudrait en parler, si on a budget on peut tjr engager quelqun

**Comment by Blond11516** [comment]
J'vais chercher sur skillshare voir ce que ça pourrait coûter

**Comment by Blond11516** [comment]
Ouais so skillshare c'était pas du tout ce que je pensais mais j'ai regardé rapido sur fiverr pis on peut avoir un logo dans n'importe quel style avec les fichiers source pour quelques dizaines de dollars CAD (j'en ai vu qui le font pour 20$)

**Comment by Blond11516** [comment]
Doc de brainstorm : https://docs.google.com/document/d/1-MwK4fOr--88BFLcU_7ZDp2DkAKTofJ6xAi4FqSEckA/edit

À regarder sur fiverr/autres sites pour le fonctionnement, les prix, etc.

**Comment by Blond11516** [comment]
On commence par un design contest à US$50 sur [Every Designs](https://www.everydesigns.com/). Si on a dequoi qu'on aime, tant mieux, sinon ça nous aura donné des idées pour aller vers dequoi de plus professionnel.

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/66416810-b291a380-e9cc-11e9-8581-9d757a09800a.png)

**Comment by Res260** [comment]
Nouveau logo announced
