### ISSUE TITLE
Updater la section communication du wiki

### ISSUE THREAD

**Issue by Blond11516** [JDIS/Organisation#259]
Ajouter les nouveau groupes de sciences et génie.
Mentionner que les posts Facebook sont répliqués sur Slack et Twitter.

**Comment by Res260** [comment]
y sont pas toujours répliqués sur slack pis twitter, mais souvent, c'est weird

**Comment by Blond11516** [comment]
Hmm, faudrait look into that

**Comment by Res260** [comment]
Ajouter les pages fb de fac de sciences et génie

**Comment by p-chatzi** [comment]
Alright, has been done
