### ISSUE TITLE
Retrouver les adapteurs réseaux

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#262]
On avait 10 adapteurs USB3-Ethernet

**Comment by Res260** [comment]
man je les cherche depuis un bout, aucune idée ils sont où..........

**Comment by Sytten** [comment]
dude cest fucking 150$ spas normal de perdre ca en moins d'un an

**Comment by Res260** [comment]
I know mais je sais pas quoi faire pour les retrouver

**Comment by AntoineTheb** [comment]
C'est cave, mais chercher ? Genre c'est tu perdu dans les capes, en arrière d'un étagère, en dessous du divan, etc. Ptete que quelqu'un les a empruntés, c'est quand la dernière fois qu'ils ont été utilisés ? Est-ce qu'ils ont été amenés dans une compé récemment ?

**Comment by AntoineTheb** [comment]
Faire un inventaire et le garder à jour ça serait pas pire j'pense. Genre une feuille excel qui dit quoi est où, quand c'est emprunté, retourné, avec une personne assignée de keep track des trucs quand ça sort du local.

**Comment by Sytten** [comment]
- Coveo blitz 2019
- Hackfest 2018
- CS Games 2019
- Appel à tous

**Comment by Res260** [comment]
coveo les a pas, hackfest non plus

**Comment by Res260** [comment]
jpas mal sûr qu'on les a pas apportés au cs games

**Comment by Res260** [comment]
We did not find them

**Comment by AntoineTheb** [comment]
rip
