### ISSUE TITLE
demande faee pour hackfest

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#268]
on pourrait demander genre 200$

**Comment by Res260** [comment]
@Goglu023 envoyé?

**Comment by Goglu023** [comment]
Yes. Demande envoyée pour 500$ de support. Le budget de la feuille de calcul est également mis à jour. En attente de réponse

**Comment by Res260** [comment]
tu peux fermer quand c'est envoyé @Goglu023 !
