### ISSUE TITLE
Acheter un cart à roulettes

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#269]
On a bc de stock tbh

**Comment by Sytten** [comment]
https://www.amazon.ca/GreenWise-Collapsible-Folding-Outdoor-Shopping/dp/B06XYF899H/ref=sr_1_6?keywords=cart&qid=1568739858&s=gateway&sr=8-6&th=1

**Comment by Res260** [comment]
En attente du fond de subvention

**Comment by Res260** [comment]
commandé

**Comment by Goglu023** [comment]
vu au costco de Sherbrooke: 89$ https://www.costco.ca/mac-sports-extra-large-folding-wagon.product.100509390.html

**Comment by Goglu023** [comment]
Est-ce que c'est mort avec le covid?

**Comment by Res260** [comment]
Je l'ai jamais reçu :(

**Comment by Res260** [comment]
ça venait de la chine et la chine était en full lockdown pendant ce temps là (janvier-fev) donc prob rip

**Comment by ArcticWalrus** [comment]
Nous avons fait un peu de ménage dans le local et tout est à distance.
So rip cart pour le moment.
