### ISSUE TITLE
Demander au monde de payer leur billet pour le HF

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#270]
Pour que max soit remboursé, 50$ par billet

**Comment by Res260** [comment]
@Pourliver faut aussi pas oublier qu'ils uploadent leur CV

**Comment by Pourliver** [comment]
Sent. Les gens doivent me virer 53.47 each

**Comment by Res260** [comment]
Done @Pourliver ?

**Comment by Pourliver** [comment]
Tout le monde a payer! Je leur assigne leur billet dans Eventbrite au courant de la fin de semaine.
