### ISSUE TITLE
Penser au branding de JDIS

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#28]
- Possiblement changer le nom
- Possiblement changer le logo

**Comment by Sytten** [comment]
Je crois qu'on peut assumer qu'on change pas de nom, mais est-ce qu'on change de logo?

**Comment by Pourliver** [comment]
À moins d'avoir une idée intéressante (en d'autres mots,  si @maximevaillancourt se sent créatif :p), on pourait changer, mais je ne crois pas que ce soit un besoin nécéssairement.

**Comment by maximevaillancourt** [comment]
Concernant le nom, je ne le changerais pas. Ce serait jeter notre crédibilité et notre _outreach_ actuels par la fenêtre.

Concernant le logo : je suis d'avis qu'on devrait le changer. Le logo actuel ne représente pas les valeurs et la mission de JDIS. Quelques idées à intégrer au logo : 
- Un badge/emblème à la DCI
- Des sabres laser et/ou capes de jedi
- Un laptop
- Le "vert UdeS"

**Comment by Res260** [comment]
Juliette Dekeyser de Consensus s'est portée volontaire pour tenter de faire un nouveau logo. @Pourliver devrait se charger de kickstart la discussion avec les parties intéressées

**Comment by Sytten** [comment]
Est-ce qu'on a du nouveau pour ça @Pourliver

**Comment by maximevaillancourt** [comment]
Je me suis amusé un peu. Qu'est-ce que vous pensez de ça?

## Version longue
![g9358](https://user-images.githubusercontent.com/8457808/45218453-abeaa700-b275-11e8-8945-b4e3ce5812dd.png)

## Version courte
![text9486](https://user-images.githubusercontent.com/8457808/45218455-abeaa700-b275-11e8-8688-78304bba2a8f.png)

**Comment by Res260** [comment]
Je pense qu'il y a quelque chose à faire avec ça, mais jsuis pas convaincu
du bouclier, c'est quoi le thought process derrière ça?

**Comment by maximevaillancourt** [comment]
J'ai pensé au bouclier pour représenter la tendance de JDIS à s'orienter principalement vers les défis/compétitions de sécurité. Pas plus compliqué que ça.

**Comment by Res260** [comment]
J'aimerais ben qu'on ait quelque chose qui fait un clin d'oeil à star wars, ça fait partie de notre identité imo

**Comment by Res260** [comment]
Pas de traction depuis un moment, on cancelle for now
