### ISSUE TITLE
JDIS-Academy #11: Windows Forensics (Émilio Gonzalez)

### ISSUE THREAD

**Issue by parfaitay** [JDIS/Organisation#280]
JDIS-Academy 11 : Windows Forensics par Émilio Gonzalez
Date: 25/11/19
Lieu: Génie

**Comment by Res260** [comment]
@parfaitay 

**Titre:** JDIS Academy #11: Introduction aux enquêtes numériques sur Windows

**Description:** Windows est un logiciel excessivement complexe, et cette complexité introduit des comportements souvent inconnus de ses usagers. Cet atelier vise à introduire certains concepts de "Computer Forensics" qui sont appliqués dans des équipes de réponse aux incidents ou par la police dans le cadre d'une enquête criminelle, afin de reconstruire une "scène de crime numérique".

Plus précisément, nous allons voir des exemples concrets de:
- Comment obtenir des traces d'une connexion à distance à un autre ordinateur;
- Comment trouver des preuves du branchement d'une clé USB par le passé;
- Comment récupérer des métadonnées significatives de fichiers qui ont déjà existés dans un ordinateur mais qui ont été supprimés.

Afin de faire les ateliers, téléchargez:
- La machine virtuelle d'exercice: LIEN À VENIR
- VMWare ou VirtualBox, pour rouler la machine sur votre ordinateur. La machine a besoin d'au minimum 2Go de RAM.

**Comment by Res260** [comment]
A été cancellé pcq pas assez de monde. Possiblement refaire à l'hiver, unsure
