### ISSUE TITLE
Brainstorm sur comment automatiser la publication d'événements?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#281]
Messemble que c'est un pipeline qui serait mostly automatisable...

**Comment by Blond11516** [comment]
Me semble que j'avais checké l'hiver passé pis j'avais pas trouvé de façon d'automatiser les posts dans les groupes Facebook. On peut toujours se faire un tool custom mais ce serait pas idéal.

**Comment by Res260** [comment]
perso jpense ça serait nice à considérer

--Émilio

**Comment by Res260** [comment]
Facebook ne permet pas de poster "légalement" dans plusieurs groupes facebook, il faut avoir le controle de chaque groupe et y ajouter une "app".
