### ISSUE TITLE
Poke Bergy pour un midi-conférence si ça choke avec Ubisoft

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#284]
Y m'a dit au 5@8 qu'il avait un sujet à présenter
Sinon en hiver

**Comment by Res260** [comment]
@Blond11516

**Comment by Blond11516** [comment]
Yes je fais ça cette semaine

**Comment by Blond11516** [comment]
Il est intéressé mais n'a pas la tête à ça pour l'instant, je le repoke dans 1-2 semaines

**Comment by Res260** [comment]
its happenning
