### ISSUE TITLE
Préparation des qualifications des CSGames 2020

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#287]
Date : 18 Janvier 2019

J'aimerais organiser un meetup de planification des quals durant la semaine du 11 novembre. Qui serait down, et quelle dates / heures vous irais?

TODO

- Décider de la plateforme / style de qualifications
- Décider d'avances les catégories qu'on veut représenter en challenges
- Décider des challenges nécessaires
- Trouver des gens pour faires des challenges
- Réserver un local
- Faire la pub

**Comment by Res260** [comment]
Pour la pub, si on est motivé, on pourrait faire des posts fb pour intéresser le monde dans le genre de ça

https://www.facebook.com/CompeteMcGill/photos/a.309409906144969/828069657612322/?type=3&theater

**Comment by AntoineTheb** [comment]
"Which university brosse le plus ..?"

**Comment by AntoineTheb** [comment]
@Pourliver ^ ?

**Comment by Pourliver** [comment]
On peut faire ça la semaine d'avant, mais j'ai peur que ça se fasse pas savoir assez vite dans la première semaine de la session

**Comment by tihbe** [comment]
@Res260 @Blond11516 @AntoineTheb @Pourliver Mardi 12 à 13h30 ?

**Comment by Pourliver** [comment]
Demain j'ai une rencontre pour un autre devoir de 11h30 à 12h30, soit j'arrive plus tard, où qu'on repousse de 30 minutes

**Comment by tihbe** [comment]
@Pourliver 13h30?

**Comment by Pourliver** [comment]
C'est bon pour moi then!

**Comment by Res260** [comment]
Ajd 13:30 is good pour moi too, @AntoineTheb ?

**Comment by AntoineTheb** [comment]
Yep

**Comment by Res260** [comment]
@Blond11516 jtavais oublié c'est chill?

**Comment by Blond11516** [comment]
Yes

**Comment by Res260** [comment]
Done, plus grosse qualif depuis le début de JDIS! https://docs.google.com/spreadsheets/d/1AGPkMWOp1D-14QkS2Z9rG9I3yJCBLVTBx379Fyw6Ohw/edit#gid=35556913
