### ISSUE TITLE
Où apparait notre logo? 

### ISSUE THREAD

**Issue by p-chatzi** [JDIS/Organisation#291]

**Comment by Res260** [comment]
Banner local
Banner compé
Rollups
Icone Slack
Channel Youtube
Facebook
LinkedIn
Twitter
Groupe FB
JDIS.ca
Github
EventBrite
Compte Google
TechnoDrinks
Sponsors
Sponsorship package

**Comment by p-chatzi** [comment]
Agenda (only semaine du 18nov)

**Comment by Res260** [comment]
Banner JDIS academy

**Comment by Res260** [comment]
Banner midi-conférence

**Comment by Res260** [comment]
will close for now manque juste deux mais y'ont des issues déjà
