### ISSUE TITLE
Changer nos rollups

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#295]

**Comment by Goglu023** [comment]
impression JG ou uniD

**Comment by MYSTACK555** [comment]
voir pour possiblement récupérer le méchanisme et uniquement changer l'affichage

**Comment by MYSTACK555** [comment]
Les rollups ont été commander chez uni-d le 2 ou 3 novembre et recus pour les portes ouvertes le 5 novembre.
prix: 413.91$ pour 2 rollups
