### ISSUE TITLE
Acheter des bacs de plastique pour du rangement?

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#297]
Qu'on pourrait Label, ça irait mieux que des boites de carton. Thoughts?

**Comment by Blond11516** [comment]
Avec une étagère qu'on pourrait mettre à côté du divan ce serait vraiment nice.

Quelque chose comme ça : https://www.amazon.ca/Gracious-Living-4-Shelf-Light-Shelf/dp/B0083ESFAM/ref=pd_sbs_201_19?_encoding=UTF8&pd_rd_i=B0083ESFAM&pd_rd_r=4693259f-67e9-45c4-a2ca-bf80fd66fb5f&pd_rd_w=oTvvq&pd_rd_wg=dIy2e&pf_rd_p=c7838c3c-6de6-46ad-946c-b7318af714fb&pf_rd_r=JYPZQ6JEPXD5PZMQDBDX&psc=1&refRID=JYPZQ6JEPXD5PZMQDBDX

**Comment by AntoineTheb** [comment]
Des bacs dans l'étagère ? Genre des bacs bleus en plastique. Comme ça ça fait du rangement pis ça se transporte bien

**Comment by Blond11516** [comment]
Ouais c'était à ça que je pensais
