### ISSUE TITLE
Sonder le monde en informatique

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#3]
Pour bien comprendre comment on est perçu par la communauté en informatique, leurs désirs et leurs attentes par rapport aux JDIs. Ça nous permettrait de guider nos futures décisions.

Suggestions de questions:
- Êtes vous familier avec les JDIs? (Scale, 1: Pas du tout 5: Je suis au courant de tout ce qu'ils font)
- Suivez-vous JDIs sur Facebook?
- Connaissance du Slack
- Connaissance du local des JDIs
- Niveau d'intérêt pour:
    - Financement de compétitions informatique (CSGames, HackFest, etc)
    - JDISConf
    - Midi-conférences par des commanditaires
    - Midi-info à-la club de math
    - Compétitions organisées par les JDIs
    - etc

- Commentaires généraux par rapport à l'avenir des JDIs

Données de classification:
- Faculté et programme
- Année (1ere, 2e, etc) et type de diplôme (bacc, maîtrise, doc, prof (?))

J'oublie probablement des questions pertinentes, feel free d'en proposer :)

**Comment by Sytten** [comment]
Je crois que pour la partie facebook on devrait demander le groupe et la page.
On devrait demander quels genre d'événements les intéressent et à quels ils ont participé.
On devrait publier dans la communauté informatique au sens large (jaimerais reach admin).

**Comment by Sytten** [comment]
V1: https://goo.gl/61geGi

**Comment by Res260** [comment]
J'ai laissé des commentaires dans le slack sous ton post xx

**Comment by Res260** [comment]
So si le form est pas pire là jpropose d'attendre au tout début de la session prochaine pour lancer le sondage, as le monde vont être moins occupés

**Comment by Sytten** [comment]
je suis du même avis

**Comment by Res260** [comment]
Conclusions préliminaires (wow bel oxymore Émilio) du sondage:

- Génie est sous-représenté
- JDIS est très mal introduit aux nouveaux en informatique, peu importe la faculté
- Les gens sont modérément familiers avec les activités organisées par JDIS (still great room for improvement)
- Les gens n'ont aucune idée de comment le conseil exécutif fonctionne
- La notion de "membre" est ambigu pour tout le monde
- Beaucoup de gens ne connaissaient pas l'existence de la page FB de JDIS, de son groupe FB et de son Slack.
- Pour Slack, beaucoup de répondants (48%) qui ont répondu "non" n'utilisent pas (beaucoup) Slack.
- Le financement des délégations est vu majoritairement positivement par les répondants.
- Les gens aiment JDISConf et les midis-conférence
- Les gens démontrent de l'intérêt pour des compétitions d'AI, iHack et introduction aux compétitions informatiques
- Atelier C++ et atelier sur la sécurité informatique semblent intéressant, même chose pour un atelier git (mais un peu moins)

Ce qui est ressorti des commentaires des gens:
- Manque d'introduction à JDIS/publicité pour les events/communication en général
- JDIS "feel" plus comme une organisation de Science que de Génie.
- Facebook, Slack et email seraient les moyens de communication à privilégier (à prendre comme un grain de sel)
