### ISSUE TITLE
Hoodie JDIS

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#30]
Ça serait nice un hoodie!

**Comment by Res260** [comment]
Dépend fortement du output de #28

**Comment by Res260** [comment]
Btw: faire qqchose qui référence pas à l'année permet d'en acheter d'avance et donc possiblement de sauver de l'argent

**Comment by Res260** [comment]
N'est plus en attente!

**Comment by MYSTACK555** [comment]
issue englobé par l'issue #319
