### ISSUE TITLE
Updater les photos du CE

### ISSUE THREAD

**Issue by Blond11516** [JDIS/Organisation#308]
- [x] Obtenir des photos des nouveaux membres
- [x] Prendre une photo de groupe
- [x] Updater les photos sur le site web

**Comment by Res260** [comment]
@francishamel post pic

**Comment by Res260** [comment]
@p-chatzi @Goglu023 @AndyChartier est-ce qu'un de vous peut s'en occuper?

**Comment by Goglu023** [comment]
Updater les photos sur le site web:
- y avais t'il d'autres update à apporter au site web?

**Comment by Res260** [comment]
check les autres issues y'a uhhhh #311
