### ISSUE TITLE
Explorer un volet entreprenariat 

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#31]
La demande pour l'entreprenariat est grandissante. Nous pourrions explorer ce volet.
Quelques idées:
- Partenariat avec enactus-sherbrooke (http://enactus-sherbrooke.com/)
- Midi-conférence entreprenariat

**Comment by urospet** [comment]
Je suis sensé avoir une réunion avec l'ACET bientôt pour mon projet d'entreprise, je vais en profiter pour voir s'ils seraient intéressé à faire un midi conférence

**Comment by Sytten** [comment]
Good, j'ai agendrix qui va venir plus tard cet été faire un talk

**Comment by Res260** [comment]
N'avions-nous pas dit que l'on réservait les talks pour les commanditaires?

**Comment by Res260** [comment]
My point stands?

**Comment by Res260** [comment]
Ah jpensais qu'on en avait discuté en CE pis que c'était dans le plan de commandite 🤔

**Comment by Sytten** [comment]
Pas vraiment, le truc qu'on devrait dire non c'est les objets promo durant les midi-conférences. Ce qu'on a donné comme perk c'est si une entreprise vient faire un event corpo à sherbrooke, ben on va le publier seulement s'ils sont notre commanditaire.

**Comment by Res260** [comment]
okok

**Comment by Res260** [comment]
@Sytten @urospet On garde ouvert ou on close?

**Comment by Sytten** [comment]
Close
