### ISSUE TITLE
Planifier les JDIS Games

### ISSUE THREAD

**Issue by Goglu023** [JDIS/Organisation#312]
Il faut commencer à communiquer avec nos contacts pour la planification des JDIS Games.

Voir le [Wiki](https://github.com/JDIS/guide-jdis/wiki/JDIS-Games) pour plus de détails.

**Comment by Res260** [comment]
Vicotr Frève a manifesté de l'intérêt pour aider. Il est en Génie 65 et est en session à l'été

**Comment by Goglu023** [comment]
Après la première rencontre du CE a20, les JDIS Games seront de retour à l'été 2021 😥
