### ISSUE TITLE
Acheter trophés et prix pour UnitedCTF

### ISSUE THREAD

**Issue by ArcticWalrus** [JDIS/Organisation#327]
100$ pour l'ensemble des prix
Michael s'occupe des trophés

**Comment by MYSTACK555** [comment]
Les trophées sont commandé. J'attend un téléphone de Gerry pour les récupérer et prendre la photos

**Comment by MYSTACK555** [comment]
La décision c'est porter sur les raspberry pie zerro pour les prix au gagnat du united ctf de sherbrooke.

**Comment by MYSTACK555** [comment]
j'acheterai donc 3 raspberry pi zero de chez canakit. le starter kit étant a 32.95$
![image](https://user-images.githubusercontent.com/49126593/97877696-8d648700-1ceb-11eb-816e-afd9f92790a4.png)
130.84 sur kanakit

**Comment by MYSTACK555** [comment]
Les Trophée du united et les pi reçus et distribué au gagnant et étant un vieille issue, je ferme celui-ci
