### ISSUE TITLE
Créer JDIS Academy Pointeurs

### ISSUE THREAD

**Issue by ArcticWalrus** [JDIS/Organisation#328]
À donner soit à la session d'hiver ou l'automne prochain.

**Comment by MYSTACK555** [comment]
![image](https://user-images.githubusercontent.com/49126593/133278095-25a01431-d3dd-4964-bf59-035e19bfa768.png)

**Comment by MYSTACK555** [comment]
confirmer pour lundi 27 septembre j'essaie de l'avoir pour 12h30

**Comment by MYSTACK555** [comment]
La présentation a été accomplis. Un sondage a été remplis par les participant afin d'avoir certaines statistiques. les dispositive de la présentation ajouter au repo JDIS-Academy. J'ai cependant oublier d'enregistrer la présentation.
