### ISSUE TITLE
Commandite: Répondre à Marilou (covéo) plan de commandite 2021/2022

### ISSUE THREAD

**Issue by MYSTACK555** [JDIS/Organisation#333]
vp.commandite@jdis.ca le 2021-07-29

**Comment by Capucinoxx** [comment]
envoi du plan de commandite à Marilou de Coveo en date du 2021-09-14

**Comment by MYSTACK555** [comment]
manque a recevoir le paiement.

**Comment by Capucinoxx** [comment]
paiement reçu le 13/10/2021
