### ISSUE TITLE
Commandite: Répondre à Olivier Julien (Genetec)

### ISSUE THREAD

**Issue by MYSTACK555** [JDIS/Organisation#334]
voir le message sur info@jdis.ca et/ou president@jdis.ca en date du 2021-08-09

**Comment by Capucinoxx** [comment]
envoi du plan de commandite à Genetec en date du 2021-09-14

**Comment by MYSTACK555** [comment]
Il ne semblait pas intéresser au programme de commandite. Alors nous ne publions plus leur différents post qu'il nous proposait au départ.
