### ISSUE TITLE
Carte d'affaire JDIS

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#34]
Une idée comme ça, c'est nice quand on parle avec une compagnie de laisser une trace.

**Comment by Res260** [comment]
Interesting idea, faudrait pas en faire trop en même temps though, considérant le roulement qu'on a...

**Comment by urospet** [comment]
Ou bien, des cartes général/réutilisable . Juste écrit vp president/ vp commandite, etc. avec le courriel
ou ajouter une ligne sur laquelle on écrit notre nom (mais ça fait moins professionnel ça)

**Comment by Res260** [comment]
C'est ça j'allais dire, me semble c'est un peu wack écrire son nom de façon manuscrite 🤔

**Comment by Sytten** [comment]
Je mettrais juste des cartes génériques JDIS, pas de nom

**Comment by Res260** [comment]
🤔

**Comment by Res260** [comment]
Une idée du coût @Sytten ?

**Comment by Sytten** [comment]
<40-50$ IMO

**Comment by Res260** [comment]
@ArcticWalrus Ça te tenterait tu de checker un potentiel design/combien ça coûterait?

**Comment by ArcticWalrus** [comment]
Parfait, je ferai ça en même temps que l'affiche pour la porte!

**Comment by ArcticWalrus** [comment]
@Res260 @Sytten 
J'ai une idée de base dans le drive. MédiasCom/Carte d'affaire.
Qu'est qu'on veut comme information sur la carte

**Comment by Res260** [comment]
Je sais pas si ça vaudrait la peine d'en avoir pour prezz, vice-prezz, vp commandites?

**Comment by Res260** [comment]
Sinon je mettrais qqchose genre "Organisation étudiante d'informatique à l'UdeS"

**Comment by Res260** [comment]
Ok pour recto verso @ArcticWalrus tu peux commander, on va rembourser avec une facture

**Comment by ArcticWalrus** [comment]
#256 On attend notre nouveau logo

**Comment by Res260** [comment]
N'est plus en attente!

**Comment by Res260** [comment]
F
