### ISSUE TITLE
Mise à jour de l'écusson JDIS

### ISSUE THREAD

**Issue by Capucinoxx** [JDIS/Organisation#341]
Nous avons actuellement un écusson JDIS pour les bandanas avec l'ancien logo de JDIS, il pourrait être intéressant de le mettre aux goûts du jour en faisant une demande de mise à jour. 

Il faudrait aussi promouvoir cet écusson pour nos participants en génie, voir les conditions d'obtention de cet écusson.

**Comment by jactymilena** [comment]
Courriel envoyé pour updater l'écusson.
![image](https://user-images.githubusercontent.com/47018467/179405328-54933042-b4a6-49ff-bfe3-0dd25380d4e9.png)

**Comment by jactymilena** [comment]
L'écusson a été mise à jour à l'automne 2022. Il devrait être disponible pour les membres en génie.
