### ISSUE TITLE
Achat cable RS232 (DB-9) femelle + Adapteur null-modem

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#38]
On a juste un cable male et parfois meme avec l'inverseur femelle-femelle on peut pas se connecter (a cause des trucs pour visser). 
Genre: https://www.amazon.ca/DTECH-Female-Adapter-Support-Windows/dp/B01N0HLKP0/ref=sr_1_7?ie=UTF8&qid=1530753610&sr=8-7&keywords=female+rs232+to+usb

Parfois aussi il faut du null-modem (en gros inverser le RX et TX): https://www.amazon.ca/Startech-NM9FF-Rs232-Serial-Adapter-F/dp/B000DZH4V0/ref=sr_1_9?s=electronics&ie=UTF8&qid=1530753663&sr=1-9&keywords=rs232+null+modem

**Comment by Res260** [comment]
Voir #46
