### ISSUE TITLE
Avoir une liste de commanditaires à poker pour septembre

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#44]

**Comment by urospet** [comment]
ElementAI

**Comment by Res260** [comment]
PMC Tire?

**Comment by Sytten** [comment]
j'en avais déjà jasé avec eux, ils avaient l'air ouverts

**Comment by Res260** [comment]
need moar

**Comment by Res260** [comment]
Jpourrais essayer NMédia peut-être haha

**Comment by Res260** [comment]
Qui s'occupe de ça?

**Comment by Sytten** [comment]
Uros quand y va avoir du temps

**Comment by Res260** [comment]
Classcraft pourrait être intéressant aussi imo

**Comment by urospet** [comment]
Bonne idée ClassCraft

**Comment by urospet** [comment]
J'ai contacté ElementAI et ZimmerCas
