### ISSUE TITLE
Midi-conférences Automne  2018

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#45]
Trois slots: 12 septembre, 3 octobre et 14 novembre.

À faire: contacter les commanditaires avec ces trois dates dispos.

**Comment by Res260** [comment]
J'ai contacté Coveo, espace inc, desjardins et Sherweb pour les midi-conférence

**Comment by Res260** [comment]
BENTLEY 14 Novembre: il faut réserver (voir emails info@jdis)

**Comment by FelixMartel** [comment]
Journée carrière: déplacer celle du 12 septembre @Sytten

**Comment by Sytten** [comment]
Je close on a d'autres issues pour ça
