### ISSUE TITLE
Faire un readme qui a de l'allure pour le repo

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#5]
Everyone deserves a great documentation xx

**Comment by Res260** [comment]
Jpeux tu être collaborator pour me mettre assignee plz

**Comment by maximevaillancourt** [comment]
Je viens de t'ajouter comme membre de l'organisation @JDIS.

**Comment by Sytten** [comment]
Sinon on peut tjr fonctionner par PR aussi

**Comment by Res260** [comment]
Ctun peu lourd pour modifier un readme imo

**Comment by Res260** [comment]
Voilà, si c'est beau pour vous je fermerais l'issue

**Comment by Pourliver** [comment]
Personnellement, je prononce toujours "les JDIS". Donc dans une phrase comme "On veut que JDIS", je dirais à la place "On veut que les JDIS". J'sais pas pour vous, peut-être que j'sais pas parler aussi 🤔 

Otherwise, j'aime ça mate!

**Comment by Res260** [comment]
Jme posais la question actually, jtrouve que "les JDIS" sonne mieux, mais
jme demande si c'est grammaticalement correct de l'écrire as such...


--Émilio


2018-04-19 8:48 GMT-04:00 Maxime Carbonneau <notifications@github.com>:

**Comment by Sytten** [comment]
les JDIS est correct, j'aime mieux ne pas utiliser "les" quand je parle d'une entité. Je reserve "les" lorsque je parle des membres.

**Comment by Res260** [comment]
Ma prof de Français m'a dit de l'écrire "les JDIS" et l'OQLF semble corroborer: http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3393 (tho ça parle pas d'accronyme)
