### ISSUE TITLE
Bénévolat oktoberfest

### ISSUE THREAD

**Issue by FelixMartel** [JDIS/Organisation#50]
- Faire un appel de participation
- Disponibilté par case horaire
- Soumettre le formulaire pour 7 septembre

**Comment by Res260** [comment]
J'en ferais la journée du vendredi

**Comment by FelixMartel** [comment]
Soumis. En attente de réponse.

**Comment by Res260** [comment]
rétro et fermer l'issue @FelixMartel @Sytten ?

**Comment by FelixMartel** [comment]
Retro:
1 particpant hors CE
À penser :
+ Faire l'appel plus tôt
+ Mettre en évdience les dates hors octo
