### ISSUE TITLE
Mettre à jour notre liste de contacts

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#59]

**Comment by Res260** [comment]
on parle de quelle liste là?

**Comment by Sytten** [comment]
Celle dans le guide JDIS, jessaye de centraliser tout la

**Comment by Res260** [comment]
Y'a quoi à changer @Sytten ?

**Comment by Sytten** [comment]
Maybe le format, je le trouve pas clair?

**Comment by Sytten** [comment]
Maybe le format, je le trouve pas clair?

**Comment by Res260** [comment]
"y faut que ça soit utile" - @Sytten 2019

**Comment by Res260** [comment]
rip
