### ISSUE TITLE
Réserver la salle

### ISSUE THREAD

**Issue by francishamel** [JDIS/Organisation#60]
- Le centre culturel ont une réservation provisoire pour toute les salles le 27 octobre. Ils vont le relancer en lui demandant de me donner une réponse d’ici la semaine prochaine et ils me réécrivent quand ils auront une réponse.

- Peut-être aller réserver la salle du carrefour de l'information si jamais

**Comment by samdus** [comment]
C'est réservé. Il ne manque qu'à donner le chèque de dépôt. Ça sera fait vendredi.

**Comment by Res260** [comment]
Been done
