### ISSUE TITLE
Créer l'event eventbrite

### ISSUE THREAD

**Issue by francishamel** [JDIS/Organisation#61]
Mostly un copy-paste de l'event de l'année passée

**Comment by francishamel** [comment]
Manque la description et la salle

**Comment by francishamel** [comment]
Manque le commanditaire principal et la salle pour préciser c'est où sur l'event!

**Comment by samdus** [comment]
Selon le contrat qu'on a avec le centre culturel, on doit ajouter le texte suivant:

Je comprends que des images seront captées lors de cet événement en vue d’une diffusion sur le web. L’organisateur de
l’événement [nom de l’entité/personne organisatrice] pourrait ainsi capter, fixer et diffuser des images de ma personne et/ou ma
voix dans le cadre de [nom de l’activité ou de l’événement], sur tout support, par tout procédé et par tout moyen. Cette captation
sera diffusée [indiquer ici le moment, la durée, le média et autres détails pertinents]. Si je ne consens pas à la captation et à la
diffusion de ces images, il est de ma responsabilité de me déplacer hors du champ de la caméra et du microphone utilisés pour
la captation.

**Comment by Res260** [comment]
lmao chill

--Émilio

**Comment by Sytten** [comment]
https://www.eventbrite.ca/e/jdisconf-2018-tickets-50050043026
