### ISSUE TITLE
Réserver les salles pour les midis-conférences

### ISSUE THREAD

**Issue by francishamel** [JDIS/Organisation#62]
Il faudrait s'assurer de louer une salle qui n'a pas de cours finissant à 12h30 pour avoir le temps de placer les choses.

**Comment by francishamel** [comment]
- 3 octobre
- 14 novembre

**Comment by Res260** [comment]
Est-ce qu'on en avait un le 19 sept finalement?

**Comment by Sytten** [comment]
Non je me suis dit qu'avec le 5@7 le 24 septembre on avait assez de trucs

**Comment by Res260** [comment]
le d7-3016?

--Émilio

**Comment by francishamel** [comment]
oui!

**Comment by francishamel** [comment]
D7-3016 confirmé pour le 14 novembre. Je vais aller voir en sciences pour le 3 octobre,

**Comment by Res260** [comment]
On peut fermer jpense
