### ISSUE TITLE
Créer l'event pour le midi-conférence du 3 octobre (coveo)

### ISSUE THREAD

**Issue by francishamel** [JDIS/Organisation#63]
Il faut savoir le sujet avant de créer l'event

**Comment by Res260** [comment]
Partir de mon template pour le midi-conférence à Bergy et pas oublier de mettre le logo de coveo

**Comment by Sytten** [comment]
Cool je savais pas si on avait un template pour la banner!

**Comment by Res260** [comment]
C'est un .ps so si vous avez pas photoshop jpeux m'en occuper c'est pas ben
ben compliqué

**Comment by francishamel** [comment]
Le sujet: la transition vers le CIDC dans un projet déjà entamé (Devops)

**Comment by Res260** [comment]
been done
