### ISSUE TITLE
Changer le nom de la page pour "JDIS - Jeux et ...." au lieu de "Jeux et .... - JDIS"

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#67]
Information importante au début... Thoughts?

**Comment by Sytten** [comment]
Meeeeh Faudrait que je check comment les autres font

**Comment by Res260** [comment]
DCI l'a first, CFI aussi, c'est juste plus logique parce qu'on dit toujours
JDIS et l'écran de personne est assez grande sur mobile pour afficher JDIS
:p

**Comment by Res260** [comment]
done lol
