### ISSUE TITLE
Utiliser la journée carrière pour augmenter la reconnaissance de JDIS auprès des entreprises

### ISSUE THREAD

**Issue by Res260** [JDIS/Organisation#68]
On a un talk de confirmé pour JDISConf à cause de @samdus et qu'il a parlé de JDISConf à des entreprises à la journée carrière. 

On peut certainement faire la même chose avec des commanditaires généraux. Toutes les entreprises là ont comme but de recruter et on peut miser sur le fait qu'on peut grandement faciliter leur contact avec les étudiant-e-s et on peut le montrer facilement (midi-conférences, événements corpos, jdisconf). Les entreprises là paient déjà pour se pointer aux journées carrières.

Je pense que si on joue ça comme du monde next year, y'a moyen de pump up nos commandites de façon significative. Genre pas pousser full fort, mais mettons juste moi quand je me suis pointé avec mon shirt JDIS l'année passée, je me le suis fait remarquer genre 3 fois lol.

**Comment by Sytten** [comment]
C'est ça que j'ai fait l'an passé et j'ai eu la commandite de Sherweb de même.

**Comment by Res260** [comment]
Done, ça marche bien quand on est 2 et on a des matching tshirts de JDIS!
