### ISSUE TITLE
Renouvellement de la commandite de Sherweb

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#70]
- Expiration: 2018-10-04
- Trouver le contact
- Transférer les courriels

**Comment by Sytten** [comment]
Ok bon je crois quon a tout donc faudrait faire l'annonce sur la page facebook

**Comment by Res260** [comment]
On a l'argent?

**Comment by Sytten** [comment]
Très probablement, @AlexLaRochelle peux-tu confirmer

**Comment by AlexLaRochelle** [comment]
va falloir que jattende le relevé de compte

**Comment by Res260** [comment]
va falloir faire l'annonce + changer la banner fb

**Comment by Sytten** [comment]
true en revenant

**Comment by Res260** [comment]
Annonce faite, changer banner fb j'attend le fichier de @Sytten

**Comment by Sytten** [comment]
Faudrait mettre a jour le doc des commanditaires pour savoir quand les poker

**Comment by Res260** [comment]
Je l'ai fait genre en novembre jpense
