### ISSUE TITLE
Closer les demandes de fonds

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#72]
- Quelles sont les demandes en cours?
- As-tu reçu des paiements?

**Comment by Sytten** [comment]
@AlexLaRochelle quand tu vas aller voir la comptable ça serait bien de nous informer pour les paiements

**Comment by AlexLaRochelle** [comment]
Dont know tbh

**Comment by Res260** [comment]
@AlexLaRochelle Well t'iras voir xd

**Comment by Res260** [comment]
![image](https://user-images.githubusercontent.com/14599855/50868282-bd0b0800-137c-11e9-9dce-4ba506d6d321.png)

Besides HF que jviens d'envoyer, y'a 4 demandes pas complétées @Sytten

**Comment by Sytten** [comment]
Je sais faut que je men occupe, pas eu le temps

**Comment by Res260** [comment]
Reste JDISConf, y'a un issue pour ça
