### ISSUE TITLE
Événements formfintech

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#84]
J'ai parlé avec quelqu’un de FormFintech. Ils veulent continuer de collaborer.
Prochain event: 
- Career fair le 29 novembre
- Regarder si pleo est intéressé (Émile)
À penser:
- Comment ils peuvent nous aider
- Déplacement des étudiants, ils pourraient pt louer un mini-bus (à voir le coût)

**Comment by Res260** [comment]
c'est où?

**Comment by Sytten** [comment]
Montréal, ma avoir les détails bientôt

**Comment by Res260** [comment]
Si c'est juste un carreer fair pis que c'est pas à sherb d'après moi on risque d'avoir peu de monde

**Comment by Res260** [comment]
Update?

**Comment by Res260** [comment]
@Sytten ?

**Comment by Sytten** [comment]
Jai fait un post sur ca dans le groupe
