### ISSUE TITLE
Planifier les qualifications des CSGames 2019

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#86]
Comme l'an passé, a la mi janvier, on va devoir faire des qualifications pour les CS Games.

Donc on doit créer des nouveaux défis, réserver un local, mettre un budget pour la pizza.

Points a discussion :
- Est ce qu'on garde la même plateforme que l'an passé?
- Qui veut faire des challenges?
- Catégories?

**Comment by Pourliver** [comment]
Personnellement, je trouve CTFd plus simple et plus agréable, je peux aussi fournir des VMs sur le cloud si certains défi en ont besoin.

J'aimerais aussi faire des challenges de sécu, crypto, assembleur et maybe theoretical CS

**Comment by Res260** [comment]
Tho on perd le gros avantage de l'autre plateforme de rouler du code

**Comment by Sytten** [comment]
Ouais j'aimerais mieux utilisé notre plateforme et continuer de l'améliorer

**Comment by Res260** [comment]
Je propose le dimanche 13 janvier, la journée après Coveo Blitz. Thoughts? @Sytten @Pourliver

**Comment by Pourliver** [comment]
C'est un peu tôt dans la session selon moi, je pense que la fin de semaine d'après (19-20), ou l'autre (26-27) serait mieux.

**Comment by Res260** [comment]
L'année passée c'était autour du 19, which was en même temps que le Hackatown de poly, though jpense pas qu'il y a un event le 26.

Mon train of thoughts pour le faire plus tôt était pour pouvoir former des teams plus tôt pour des challenges et organiser plus de pratiques

**Comment by Pourliver** [comment]
Suite aux discussions du CE, la date est confirmée pour le 19 janvier et on garde notre plateforme.

Lalex, Émilio et moi pouvons tous donner un coup sur le front-end, Emile au back-end.

**Comment by Pourliver** [comment]
Je move tout ce qui est refonte dans son propre issue.

**Comment by Res260** [comment]
Le form d'inscription à la qualif est fait

**Comment by Res260** [comment]
34 personnes (en comptant local + organisateurs + remote) se sont inscrits, on choisit soon!
