### ISSUE TITLE
Faire la demande JDIS Conf a l'AGES

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#90]
Je sais pas c'est a faire pour quand, mais Alex était sensé s'en occuper

**Comment by AlexLaRochelle** [comment]
Wait je suis pas au courant de ça 👀

**Comment by Pourliver** [comment]
C'est ton nom qui était écrit dans le document d'hier :thinking:

**Comment by Res260** [comment]
c'est sûr t'es pas au courant t'étais pas aux réunions XD

mais ouain faudrait faire ça rapidement, et ne pas oublier de mettre ça
dans notre spreadsheet de demandes d'argent

--Émilio

**Comment by Res260** [comment]
@AlexLaRochelle J'ai envoyé un email jvais m'occuper de la demande jdisconf et jdisgames en même temps

**Comment by AlexLaRochelle** [comment]
@Res260 good thanks

**Comment by Res260** [comment]
Demandes envoyées. 250$ pour jdisgames pis 300$ pour jdisconf. En attente de réponse.

**Comment by Res260** [comment]
Déposé, on a eu l'argent
