### ISSUE TITLE
Mettre a jour le contact Desjardins

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#93]

**Comment by Res260** [comment]
haha @Pourliver c'est qui qui remplace mathieu

**Comment by Pourliver** [comment]
Est-ce que c'était Mathieu notre contact? 

Si oui, jusqu'en décembre c'est Mathieu. Par après, ça sera Shirley-Anne Pagé, l'une des 2 personnes qui remplace Mathieu.

**Comment by Res260** [comment]
Est-ce que t'es en contact avec elle pour lui faire part?

**Comment by Pourliver** [comment]
Ouaip! Je vois pas lui faire part de "quoi", mais j'vais lui en parler un peu.

**Comment by Res260** [comment]
Ben mettons juste lui dire qu'on existe haha pis qu'on ait un email de qui
contacter

--Émilio

**Comment by Res260** [comment]
@Pourliver Est-ce que t'as son email?

**Comment by Pourliver** [comment]
shirley-anne.page@desjardins.com, je la contacte today.

**Comment by Res260** [comment]
mis à jour dans notre laid fichier de commanditaires
