### ISSUE TITLE
Acheter les billets du CUSEC

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#94]
10 billet selon les discussions d'hier et le doc.

**Comment by FelixMartel** [comment]
On devrait avoir des codes pour réserver des billets 🎉

**Comment by Sytten** [comment]
Est-ce quon a des news de ca?

**Comment by FelixMartel** [comment]
Je sais pas trop quoi faire de ce dossier. La dernière ronde sera le 19 novembre.
Le 31 octobre il devait m'envoyer des codes la journée même.
Le 5 novembre je l'ai contacté à nouveau - pas de réponse.
Le 15 novembre je l'ai contacté à nouveau - pas de réponse.

**Comment by Res260** [comment]
Rip :)
