### ISSUE TITLE
Trouver le thème pour les CSGames

### ISSUE THREAD

**Issue by Pourliver** [JDIS/Organisation#97]
CS Paradise!
https://2019.csgames.org/

TL;DR : En 2003, Linux a ajouté la parallélisation et un nombre illimité
de threads virtuel. Les threads ont brisé l’espace temps. Chaque
threads est devenu un univers. Chaque univers = 1 université. Le
Council tente de réunir les différents universe - ities (fusionner les
threads). Les universe - ities se rejoignent abord du CS Paradise.

On doit trouver something avec des capes 🤔

**Comment by Res260** [comment]
Idées lancées: Kevin avec chandail dragon
@AntoineTheb  @Pourliver halp

**Comment by AntoineTheb** [comment]
What Happened in 2003 inc. Pop Culture, Prices and Events: http://www.thepeoplehistory.com/2003.html

Peux peut-être donner des idées

**Comment by MAGNUM81** [comment]
Considérant l'aspect "cruise ship" ... Un thème qui porte sur les ouragan? #CycloneLivesMatter

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by Res260** [comment]
Choix #1: Mcgill
Choix #2: les capes

hopefully on le sait cette semaine
