### ISSUE TITLE
Acheter les trucs demandés dans la demande FÉÉ

### ISSUE THREAD

**Issue by Sytten** [JDIS/Organisation#99]
Voir https://github.com/JDIS/Organisation/issues/46

**Comment by Res260** [comment]
À faire !

**Comment by Res260** [comment]
Update?

**Comment by Sytten** [comment]
La tablette est sous android 5.1 pis on savait pas si on voulait changer de modele (potentiellement plus cher)

**Comment by Res260** [comment]
Switches commandées?

**Comment by Res260** [comment]
tbh perso j'ai pas de problème avec une tablette sur android 5.1

**Comment by Res260** [comment]
Fait, Switches commandées, tablete fire HD à 100$ ordered et 10 adapteurs rj 45 --> usb
